// vue/demo/src/pages/UxDemo/demos/CheckboxDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import { Checkbox, MultiToggle, Toggle } from "@cjlapao/ui-kit-vue";
import type { ThemeColor } from "@cjlapao/ui-kit-vue";
import { colorOptions } from "../constants";

type CheckboxColor = ThemeColor;

const checkboxSizeOptions = [
  { label: "SM", value: "sm" },
  { label: "MD", value: "md" },
  { label: "LG", value: "lg" },
];

const checkboxAlignOptions = [
  { label: "Left", value: "left" },
  { label: "Right", value: "right" },
];

const checkboxDescriptionOptions = [
  { label: "Stacked", value: "bottom" },
  { label: "Inline", value: "inline" },
];

const checkboxColor = ref<CheckboxColor>("blue");
const checkboxSize = ref<"sm" | "md" | "lg">("md");
const checkboxAlign = ref<"left" | "right">("left");
const checkboxDescriptionPlacement = ref<"bottom" | "inline">("bottom");
const checkboxLabel = ref(true);
const checkboxDescription = ref(true);
const checkboxIndeterminate = ref(false);
const checkboxDisabled = ref(false);
const checkboxChecked = ref(true);

const checkboxToggleItems = [
  { label: "Show label", model: checkboxLabel },
  { label: "Show description", model: checkboxDescription },
  { label: "Indeterminate", model: checkboxIndeterminate },
  { label: "Disabled", model: checkboxDisabled },
];
</script>

<template>
  <PlaygroundSection
    title="Checkbox"
    label="[Checkbox]"
    description="Accessible checkbox with description layouts."
  >
    <template #controls>
      <div class="space-y-4 text-sm">
        <label class="flex flex-col gap-2">
          <span>Color</span>
          <MultiToggle
            full-width
            :options="colorOptions"
            :model-value="checkboxColor"
            size="sm"
            @update:model-value="checkboxColor = $event as CheckboxColor"
          />
        </label>
        <div class="grid gap-3 md:grid-cols-3">
          <label class="flex flex-col gap-2">
            <span>Size</span>
            <MultiToggle
              full-width
              :options="checkboxSizeOptions"
              :model-value="checkboxSize"
              size="sm"
              @update:model-value="checkboxSize = $event as 'sm' | 'md' | 'lg'"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Align</span>
            <MultiToggle
              full-width
              :options="checkboxAlignOptions"
              :model-value="checkboxAlign"
              size="sm"
              @update:model-value="checkboxAlign = $event as 'left' | 'right'"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Description</span>
            <MultiToggle
              full-width
              :options="checkboxDescriptionOptions"
              :model-value="checkboxDescriptionPlacement"
              size="sm"
              @update:model-value="
                checkboxDescriptionPlacement = $event as 'bottom' | 'inline'
              "
            />
          </label>
        </div>
        <div class="grid gap-2 md:grid-cols-3">
          <label
            v-for="item in checkboxToggleItems"
            :key="item.label"
            class="flex items-center justify-between"
          >
            <span>{{ item.label }}</span>
            <Toggle size="sm" v-model="item.model.value" />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <div class="space-y-3">
        <Checkbox
          :label="checkboxLabel ? 'Subscribe to release notes' : undefined"
          :description="
            checkboxDescription
              ? 'We will send important product updates occasionally.'
              : undefined
          "
          :description-placement="checkboxDescriptionPlacement"
          :size="checkboxSize"
          :color="checkboxColor"
          :indeterminate="checkboxIndeterminate"
          :control-align="checkboxAlign"
          :disabled="checkboxDisabled"
          v-model="checkboxChecked"
        />
        <Checkbox label="I agree to the terms" color="emerald" size="lg" />
      </div>
    </template>
  </PlaygroundSection>
</template>

// src/pages/UxDemo/demos/CheckboxDemo.tsx
// @ts-nocheck
import React, { useState } from "react";
import { PlaygroundSection } from "../PlaygroundSection";
import { Checkbox, MultiToggle, Toggle } from "../../..";
import { CheckboxColor } from "../../..";
import { colorOptions } from "../constants";

export const CheckboxDemo: React.FC = () => {
  const [checkboxColor, setCheckboxColor] = useState<CheckboxColor>("blue");
  const [checkboxSize, setCheckboxSize] = useState<"sm" | "md" | "lg">("md");
  const [checkboxAlign, setCheckboxAlign] = useState<"left" | "right">("left");
  const [checkboxDescriptionPlacement, setCheckboxDescriptionPlacement] =
    useState<"bottom" | "inline">("bottom");
  const [checkboxLabel, setCheckboxLabel] = useState(true);
  const [checkboxDescription, setCheckboxDescription] = useState(true);
  const [checkboxIndeterminate, setCheckboxIndeterminate] = useState(false);
  const [checkboxDisabled, setCheckboxDisabled] = useState(false);
  const [checkboxChecked, setCheckboxChecked] = useState(true);

  return (
    <PlaygroundSection
      title="Checkbox"
      label="[Checkbox]"
      description="Accessible checkbox with description layouts."
      controls={
        <div className="space-y-4 text-sm">
          <label className="flex flex-col gap-2">
            <span>Color</span>
            <MultiToggle
              fullWidth
              options={colorOptions}
              value={checkboxColor}
              size="sm"
              onChange={(value) => setCheckboxColor(value as CheckboxColor)}
            />
          </label>
          <div className="grid gap-3 md:grid-cols-3">
            <label className="flex flex-col gap-2">
              <span>Size</span>
              <MultiToggle
                fullWidth
                options={[
                  { label: "SM", value: "sm" },
                  { label: "MD", value: "md" },
                  { label: "LG", value: "lg" },
                ]}
                value={checkboxSize}
                size="sm"
                onChange={(value) =>
                  setCheckboxSize(value as "sm" | "md" | "lg")
                }
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Align</span>
              <MultiToggle
                fullWidth
                options={[
                  { label: "Left", value: "left" },
                  { label: "Right", value: "right" },
                ]}
                value={checkboxAlign}
                size="sm"
                onChange={(value) =>
                  setCheckboxAlign(value as "left" | "right")
                }
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Description</span>
              <MultiToggle
                fullWidth
                options={[
                  { label: "Stacked", value: "bottom" },
                  { label: "Inline", value: "inline" },
                ]}
                value={checkboxDescriptionPlacement}
                size="sm"
                onChange={(value) =>
                  setCheckboxDescriptionPlacement(value as "bottom" | "inline")
                }
              />
            </label>
          </div>
          <div className="grid gap-2 md:grid-cols-3">
            {[
              {
                label: "Show label",
                value: checkboxLabel,
                setter: setCheckboxLabel,
              },
              {
                label: "Show description",
                value: checkboxDescription,
                setter: setCheckboxDescription,
              },
              {
                label: "Indeterminate",
                value: checkboxIndeterminate,
                setter: setCheckboxIndeterminate,
              },
              {
                label: "Disabled",
                value: checkboxDisabled,
                setter: setCheckboxDisabled,
              },
            ].map((item) => (
              <label
                key={item.label}
                className="flex items-center justify-between"
              >
                <span>{item.label}</span>
                <Toggle
                  size="sm"
                  checked={item.value}
                  onChange={(event) => item.setter(event.target.checked)}
                />
              </label>
            ))}
          </div>
        </div>
      }
      preview={
        <div className="space-y-3">
          <Checkbox
            label={checkboxLabel ? "Subscribe to release notes" : undefined}
            description={
              checkboxDescription
                ? "We will send important product updates occasionally."
                : undefined
            }
            descriptionPlacement={checkboxDescriptionPlacement}
            size={checkboxSize}
            color={checkboxColor}
            indeterminate={checkboxIndeterminate}
            controlAlign={checkboxAlign}
            checked={checkboxChecked}
            disabled={checkboxDisabled}
            onChange={(event) => setCheckboxChecked(event.target.checked)}
          />
          <Checkbox label="I agree to the terms" color="emerald" size="lg" />
        </div>
      }
    />
  );
};
