// vue/demo/src/pages/UxDemo/demos/ButtonDemo.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
  Button,
  Toggle,
  MultiToggle,
  Select,
  TRUE_COLORS,
  BUTTON_VARIANTS,
  CONTROL_SIZES,
} from "@cjlapao/ui-kit-vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import {
  trueColorOptions,
  buttonVariantAllOptions,
  controlSizeOptions,
  buttonWeightOptions,
  glassVibrancyOptions,
  glassOpacityOptions,
  pillSpecularOptions,
} from "../constants";
import type {
  ButtonVariant,
  ButtonSize,
  ButtonWeight,
  TrueColor,
  GlassVibrancy,
  GlassOpacity,
  SpecularMode,
} from "@cjlapao/ui-kit-vue";

const buttonVariant = ref<ButtonVariant>("solid");
const buttonSize = ref<ButtonSize>("md");
const buttonWeight = ref<ButtonWeight>("normal");
const buttonColor = ref<TrueColor>("blue");
const buttonLoading = ref(false);
const buttonDisabled = ref(false);
const buttonActive = ref(false);
const buttonGlass = ref(false);
const buttonAccent = ref(false);
const buttonIconOnly = ref(false);
const buttonFullWidth = ref(false);
const buttonShowLeadingIcon = ref(false);
const buttonShowTrailingIcon = ref(false);
const buttonIconColorOn = ref(false);
const buttonIconColor = ref("#ef4444");
const buttonTooltip = ref(false);
const vibrancy = ref<GlassVibrancy>("medium");
const glassOpacity = ref<GlassOpacity>("frosted");
const specularMode = ref<SpecularMode>("none");
const onGlass = ref(false);

const leading = computed(() => (buttonShowLeadingIcon.value ? "Search" : undefined));
const trailing = computed(() => (buttonShowTrailingIcon.value ? "ArrowRight" : undefined));
// Icon-only buttons need a glyph to show; fall back to one when no leading
// icon is selected so the matrices don't render empty boxes.
const glyph = computed(() =>
  buttonIconOnly.value ? (leading.value ?? "Star") : leading.value,
);

const shared = computed(() => ({
  variant: buttonVariant.value,
  color: buttonColor.value,
  size: buttonSize.value,
  weight: buttonWeight.value,
  loading: buttonLoading.value,
  disabled: buttonDisabled.value,
  active: buttonActive.value,
  glass: buttonGlass.value,
  accent: buttonAccent.value,
  iconOnly: buttonIconOnly.value,
  fullWidth: buttonFullWidth.value,
  vibrancy: vibrancy.value,
  glassOpacity: glassOpacity.value,
  specularMode: specularMode.value,
  leadingIcon: glyph.value,
  trailingIcon: trailing.value,
  iconColor: buttonIconColorOn.value ? buttonIconColor.value : undefined,
  tooltip: buttonTooltip.value ? "A button with a tooltip" : undefined,
}));

// Fixed conditions for the reference examples — each block varies exactly
// one dimension and never moves with the controls.
const example = {
  color: "blue" as TrueColor,
  size: "md" as ButtonSize,
  weight: "normal" as ButtonWeight,
};

const stateToggles = [
  { label: "Loading", model: buttonLoading },
  { label: "Disabled", model: buttonDisabled },
  { label: "Active (pressed)", model: buttonActive },
  { label: "Glass", model: buttonGlass },
  { label: "Accent", model: buttonAccent },
  { label: "Icon only", model: buttonIconOnly },
  { label: "Full width", model: buttonFullWidth },
  { label: "Leading icon", model: buttonShowLeadingIcon },
  { label: "Trailing icon", model: buttonShowTrailingIcon },
  { label: "Icon color", model: buttonIconColorOn },
  { label: "Tooltip", model: buttonTooltip },
  { label: "On a glass panel", model: onGlass },
];
</script>

<template>
  <PlaygroundSection
    title="Buttons"
    label="[Button]"
    description="Experiment with variants, weights, and icon options."
  >
    <template #controls>
      <div class="space-y-4">
        <div class="grid gap-4 md:grid-cols-2">
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Color
            </span>
            <Select
              :model-value="buttonColor"
              size="sm"
              @update:model-value="buttonColor = $event as TrueColor"
            >
              <option
                v-for="option in trueColorOptions"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </option>
            </Select>
          </div>
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Variant
            </span>
            <Select
              :model-value="buttonVariant"
              size="sm"
              aria-label="Variant"
              @update:model-value="buttonVariant = $event as ButtonVariant"
            >
              <option
                v-for="option in buttonVariantAllOptions"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </option>
            </Select>
          </div>
        </div>
        <div class="grid gap-4 md:grid-cols-2">
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Size
            </span>
            <MultiToggle
              full-width
              :options="controlSizeOptions"
              :model-value="buttonSize"
              size="sm"
              @update:model-value="buttonSize = $event as ButtonSize"
            />
          </div>
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Weight
            </span>
            <MultiToggle
              full-width
              :options="buttonWeightOptions"
              :model-value="buttonWeight"
              size="sm"
              @update:model-value="buttonWeight = $event as ButtonWeight"
            />
          </div>
        </div>
        <div class="grid grid-cols-2 gap-2 md:grid-cols-3">
          <Toggle
            v-for="item in stateToggles"
            :key="item.label"
            size="sm"
            :label="item.label"
             v-model="item.model.value"
           />
         </div>
         <div v-if="buttonIconColorOn" class="space-y-2">
           <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
             Icon color (override)
           </span>
           <div class="flex items-center gap-2">
             <input
               type="color"
               :value="buttonIconColor"
               @input="buttonIconColor = ($event.target as HTMLInputElement).value"
               class="h-9 w-14 cursor-pointer rounded border border-neutral-300 bg-transparent p-1 dark:border-neutral-600"
               aria-label="Icon color"
             />
             <span class="font-mono text-sm text-neutral-500 dark:text-neutral-400">
               {{ buttonIconColor }}
             </span>
           </div>
         </div>
         <div v-if="buttonGlass" class="grid gap-4 md:grid-cols-3">
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Vibrancy
            </span>
            <MultiToggle
              full-width
              :options="glassVibrancyOptions"
              :model-value="String(vibrancy)"
              size="sm"
              @update:model-value="vibrancy = $event as GlassVibrancy"
            />
          </div>
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Fill
            </span>
            <MultiToggle
              full-width
              :options="glassOpacityOptions"
              :model-value="String(glassOpacity)"
              size="sm"
              @update:model-value="glassOpacity = $event as GlassOpacity"
            />
          </div>
          <div class="space-y-2">
            <span class="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Specular
            </span>
            <MultiToggle
              full-width
              :options="pillSpecularOptions"
              :model-value="specularMode"
              size="sm"
              @update:model-value="specularMode = $event as SpecularMode"
            />
          </div>
        </div>
      </div>
    </template>
    <template #preview>
      <div class="space-y-6 p-4">
        <!-- The only block the controls drive. The button sits in a plain
             (block) surface so `inline-flex` sizes it to its content — a
             `flex flex-col` parent would stretch it full width and the
             Full-width toggle would have nothing to do. "On a glass panel"
             just swaps that surface for a coloured one the glass blur reads. -->
        <div class="flex flex-col gap-2">
          <span class="text-[11px] font-semibold uppercase tracking-wide opacity-60">
            Current settings
          </span>
          <div
            :class="
              onGlass
                ? 'rounded-2xl bg-gradient-to-br from-sky-400 via-violet-400 to-rose-300 p-6 dark:from-sky-600 dark:via-violet-600 dark:to-rose-500'
                : 'rounded-2xl border border-neutral-200 bg-neutral-50 p-6 dark:border-neutral-800 dark:bg-neutral-900'
            "
          >
            <Button v-bind="shared">Button Label</Button>
          </div>
        </div>

        <!-- Fixed reference specimens — none of these move with the controls. -->
        <div class="space-y-6 rounded-2xl border border-neutral-200 p-4 dark:border-neutral-800">
          <div class="flex flex-col gap-2">
            <span class="text-[11px] font-semibold uppercase tracking-wide opacity-60">
              Every variant — fixed tone, size, and weight
            </span>
            <div class="grid gap-3 md:grid-cols-2">
              <Button
                v-for="each in BUTTON_VARIANTS"
                :key="each"
                v-bind="example"
                :variant="each"
              >
                {{ each }}
              </Button>
            </div>
          </div>

          <div class="flex flex-col gap-2">
            <span class="text-[11px] font-semibold uppercase tracking-wide opacity-60">
              Size ladder — solid, fixed tone
            </span>
            <div class="flex flex-wrap items-center gap-3">
              <Button
                v-for="each in CONTROL_SIZES"
                :key="each"
                v-bind="example"
                variant="solid"
                :size="each"
              >
                {{ each }}
              </Button>
            </div>
          </div>

          <div class="flex flex-col gap-2">
            <span class="text-[11px] font-semibold uppercase tracking-wide opacity-60">
              All {{ TRUE_COLORS.length }} tones — solid, fixed size
            </span>
            <div class="grid gap-2 md:grid-cols-3">
              <Button
                v-for="each in TRUE_COLORS"
                :key="each"
                v-bind="example"
                variant="solid"
                :color="each"
              >
                {{ each }}
              </Button>
            </div>
          </div>

          <div class="flex flex-col gap-2">
            <span class="text-[11px] font-semibold uppercase tracking-wide opacity-60">
              Pressed (active) — the persistent &quot;on&quot; state
            </span>
            <div class="grid gap-3 md:grid-cols-2">
              <Button
                v-for="each in ['solid', 'soft', 'outline', 'ghost'] as ButtonVariant[]"
                :key="each"
                v-bind="example"
                :variant="each"
                active
              >
                {{ each }}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </template>
  </PlaygroundSection>
</template>

// react/demo/src/pages/UxDemo/demos/ButtonDemo.tsx
import React, { useState } from "react";
import {
  Button,
  Toggle,
  MultiToggle,
  Select,
  TRUE_COLORS,
  BUTTON_VARIANTS,
  CONTROL_SIZES,
  type ButtonVariant,
  type ButtonSize,
  type ButtonWeight,
  type TrueColor,
  type GlassVibrancy,
  type GlassOpacity,
  type SpecularMode,
} from "@cjlapao/ui-kit";
import { PlaygroundSection } from "../PlaygroundSection";
import {
  trueColorOptions,
  buttonVariantAllOptions,
  controlSizeOptions,
  buttonWeightOptions,
  glassVibrancyOptions,
  glassOpacityOptions,
  panelSpecularOptions,
} from "../constants";

const Caption: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <span className="text-[11px] font-semibold uppercase tracking-wide opacity-60">
    {children}
  </span>
);

export const ButtonDemo: React.FC = () => {
  const [buttonVariant, setButtonVariant] = useState<ButtonVariant>("solid");
  const [buttonSize, setButtonSize] = useState<ButtonSize>("md");
  const [buttonWeight, setButtonWeight] = useState<ButtonWeight>("normal");
  const [buttonColor, setButtonColor] = useState<TrueColor>("blue");
  const [buttonLoading, setButtonLoading] = useState(false);
  const [buttonDisabled, setButtonDisabled] = useState(false);
  const [buttonActive, setButtonActive] = useState(false);
  const [buttonGlass, setButtonGlass] = useState(false);
  const [buttonAccent, setButtonAccent] = useState(false);
  const [buttonIconOnly, setButtonIconOnly] = useState(false);
  const [buttonFullWidth, setButtonFullWidth] = useState(false);
  const [buttonShowLeadingIcon, setButtonShowLeadingIcon] = useState(false);
  const [buttonShowTrailingIcon, setButtonShowTrailingIcon] = useState(false);
  const [buttonIconColorOn, setButtonIconColorOn] = useState(false);
  const [buttonIconColor, setButtonIconColor] = useState("#ef4444");
  const [buttonTooltip, setButtonTooltip] = useState(false);
  const [vibrancy, setVibrancy] = useState<GlassVibrancy>("medium");
  const [glassOpacity, setGlassOpacity] = useState<GlassOpacity>("frosted");
  const [specularMode, setSpecularMode] = useState<SpecularMode>("none");
  const [onGlass, setOnGlass] = useState(false);

  const leading = buttonShowLeadingIcon ? "Search" : undefined;
  const trailing = buttonShowTrailingIcon ? "ArrowRight" : undefined;
  // Icon-only buttons need a glyph to show; fall back to one when no leading
  // icon is selected so the matrices don't render empty boxes.
  const glyph = buttonIconOnly ? (leading ?? "Star") : leading;

  const shared: React.ComponentProps<typeof Button> = {
    variant: buttonVariant,
    color: buttonColor,
    size: buttonSize,
    weight: buttonWeight,
    loading: buttonLoading,
    disabled: buttonDisabled,
    active: buttonActive,
    glass: buttonGlass,
    accent: buttonAccent,
    iconOnly: buttonIconOnly,
    fullWidth: buttonFullWidth,
    vibrancy,
    glassOpacity,
    specularMode,
    leadingIcon: glyph,
    trailingIcon: trailing,
    iconColor: buttonIconColorOn ? buttonIconColor : undefined,
    tooltip: buttonTooltip ? "A button with a tooltip" : undefined,
  };

  // Fixed conditions for the reference examples below. Those blocks never
  // change with the controls above — each one varies exactly one named
  // dimension (variant / size / tone / active) so it reads as a stable
  // specimen, not a second live button.
  const example: React.ComponentProps<typeof Button> = {
    color: "blue",
    size: "md",
    weight: "normal",
  };

  const stateToggle = (
    label: string,
    value: boolean,
    setter: (value: boolean) => void,
  ) => (
    <Toggle
      size="sm"
      label={label}
      checked={value}
      onChange={(event) => setter(event.target.checked)}
    />
  );

  return (
    <PlaygroundSection
      title="Buttons"
      label="[Button]"
      description="Experiment with variants, weights, and icon options."
      controls={
        <div className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                Color
              </span>
              <Select
                size="sm"
                value={buttonColor}
                onChange={(event) =>
                  setButtonColor(event.target.value as TrueColor)
                }
                aria-label="Color"
              >
                {trueColorOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </div>
            <div className="space-y-2">
              <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                Variant
              </span>
              <Select
                size="sm"
                value={buttonVariant}
                onChange={(event) =>
                  setButtonVariant(event.target.value as ButtonVariant)
                }
                aria-label="Variant"
              >
                {buttonVariantAllOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </div>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                Size
              </span>
              <MultiToggle
                fullWidth
                options={controlSizeOptions}
                value={buttonSize}
                size="sm"
                onChange={(value) => setButtonSize(value as ButtonSize)}
              />
            </div>
            <div className="space-y-2">
              <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                Weight
              </span>
              <MultiToggle
                fullWidth
                options={buttonWeightOptions}
                value={buttonWeight}
                size="sm"
                onChange={(value) => setButtonWeight(value as ButtonWeight)}
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-2 md:grid-cols-3">
            {stateToggle("Loading", buttonLoading, setButtonLoading)}
            {stateToggle("Disabled", buttonDisabled, setButtonDisabled)}
            {stateToggle("Active (pressed)", buttonActive, setButtonActive)}
            {stateToggle("Glass", buttonGlass, setButtonGlass)}
            {stateToggle("Accent", buttonAccent, setButtonAccent)}
            {stateToggle("Icon only", buttonIconOnly, setButtonIconOnly)}
            {stateToggle("Full width", buttonFullWidth, setButtonFullWidth)}
            {stateToggle(
              "Leading icon",
              buttonShowLeadingIcon,
              setButtonShowLeadingIcon,
            )}
            {stateToggle(
              "Trailing icon",
              buttonShowTrailingIcon,
              setButtonShowTrailingIcon,
            )}
            {stateToggle("Icon color", buttonIconColorOn, setButtonIconColorOn)}
            {stateToggle("Tooltip", buttonTooltip, setButtonTooltip)}
            {stateToggle("On a glass panel", onGlass, setOnGlass)}
          </div>
          {buttonIconColorOn && (
            <div className="space-y-2">
              <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                Icon color (override)
              </span>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={buttonIconColor}
                  onChange={(event) => setButtonIconColor(event.target.value)}
                  className="h-9 w-14 cursor-pointer rounded border border-neutral-300 bg-transparent p-1 dark:border-neutral-600"
                  aria-label="Icon color"
                />
                <span className="font-mono text-sm text-neutral-500 dark:text-neutral-400">
                  {buttonIconColor}
                </span>
              </div>
            </div>
          )}
          {buttonGlass && (
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                  Vibrancy
                </span>
                <MultiToggle
                  fullWidth
                  options={glassVibrancyOptions}
                  value={String(vibrancy)}
                  size="sm"
                  onChange={(value) => setVibrancy(value as GlassVibrancy)}
                />
              </div>
              <div className="space-y-2">
                <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                  Fill
                </span>
                <MultiToggle
                  fullWidth
                  options={glassOpacityOptions}
                  value={String(glassOpacity)}
                  size="sm"
                  onChange={(value) =>
                    setGlassOpacity(value as GlassOpacity)
                  }
                />
              </div>
              <div className="space-y-2">
                <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
                  Specular
                </span>
                <MultiToggle
                  fullWidth
                  options={panelSpecularOptions}
                  value={specularMode}
                  size="sm"
                  onChange={(value) =>
                    setSpecularMode(value as SpecularMode)
                  }
                />
              </div>
            </div>
          )}
        </div>
      }
      preview={
        <div className="space-y-6 p-4">
          {/* The only block the controls drive. The button sits in a plain
              (block) surface so `inline-flex` sizes it to its content — a
              `flex flex-col` parent would stretch it full width and the
              Full-width toggle would have nothing to do. "On a glass panel"
              just swaps that surface for a coloured one the glass blur can
              read. */}
          <div className="flex flex-col gap-2">
            <Caption>Current settings</Caption>
            <div
              className={
                onGlass
                  ? "rounded-2xl bg-gradient-to-br from-sky-400 via-violet-400 to-rose-300 p-6 dark:from-sky-600 dark:via-violet-600 dark:to-rose-500"
                  : "rounded-2xl border border-neutral-200 bg-neutral-50 p-6 dark:border-neutral-800 dark:bg-neutral-900"
              }
            >
              <Button {...shared}>Button Label</Button>
            </div>
          </div>

          {/* Fixed reference specimens — none of these move with the controls. */}
          <div className="space-y-6 rounded-2xl border border-neutral-200 p-4 dark:border-neutral-800">
            <div className="flex flex-col gap-2">
              <Caption>
                Every variant — fixed tone, size, and weight
              </Caption>
              <div className="grid gap-3 md:grid-cols-2">
                {BUTTON_VARIANTS.map((each) => (
                  <Button key={each} {...example} variant={each}>
                    {each}
                  </Button>
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <Caption>Size ladder — solid, fixed tone</Caption>
              <div className="flex flex-wrap items-center gap-3">
                {CONTROL_SIZES.map((each) => (
                  <Button key={each} {...example} variant="solid" size={each}>
                    {each}
                  </Button>
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <Caption>All {TRUE_COLORS.length} tones — solid, fixed size</Caption>
              <div className="grid gap-2 md:grid-cols-3">
                {TRUE_COLORS.map((each) => (
                  <Button key={each} {...example} variant="solid" color={each}>
                    {each}
                  </Button>
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <Caption>
                Pressed (active) — the persistent &quot;on&quot; state
              </Caption>
              <div className="grid gap-3 md:grid-cols-2">
                {(["solid", "soft", "outline", "ghost"] as const).map(
                  (each) => (
                    <Button key={each} {...example} variant={each} active>
                      {each}
                    </Button>
                  ),
                )}
              </div>
            </div>
          </div>
        </div>
      }
    />
  );
};
