// vue/demo/src/pages/UxDemo/demos/SelectDemo.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import {
  MultiToggle,
  Panel,
  Select,
  Toggle,
  CONTROL_SIZES,
  INPUT_VARIANTS,
  TRUE_COLORS,
} from "@cjlapao/ui-kit-vue";
import type {
  SelectSize,
  SelectValidationStatus,
  SelectVariant,
  TrueColor,
} from "@cjlapao/ui-kit-vue";
import {
  controlSizeOptions,
  inputValidationOptions,
  inputVariantOptions,
  trueColorOptions,
} from "../constants";

const REGIONS = ["eu-west-1", "us-east-1", "ap-south-1", "sa-east-1"];

const variant = ref<SelectVariant>("flat");
const size = ref<SelectSize>("md");
const tone = ref<TrueColor>("blue");
const validationStatus = ref<SelectValidationStatus>("none");

const value = ref("");
const leadingIcon = ref(false);
const placeholder = ref(true);
const hideCaret = ref(false);
const multiple = ref(false);
const disabled = ref(false);
const onGlass = ref(false);

const resolvedLeadingIcon = computed(() =>
  leadingIcon.value ? "Globe" : undefined,
);

const stateToggles = [
  { label: "Leading icon", model: leadingIcon },
  { label: "Placeholder", model: placeholder },
  { label: "Hide caret", model: hideCaret },
  { label: "Multiple", model: multiple },
  { label: "Disabled", model: disabled },
  { label: "On a glass panel", model: onGlass },
];
</script>

<template>
  <PlaygroundSection
    title="Select"
    label="[Select]"
    description="The native dropdown, with the platform caret replaced by the kit's. Surface, size and tone come from the shared scales, so it lines up with the Input and SearchBar beside it."
  >
    <template #controls>
      <div class="space-y-5 text-sm">
        <label class="flex flex-col gap-2">
          <span class="text-xs font-medium uppercase tracking-wide opacity-70">
            Variant
          </span>
          <MultiToggle
            full-width
            size="sm"
            :options="inputVariantOptions"
            :model-value="variant"
            @update:model-value="variant = $event as SelectVariant"
          />
        </label>

        <div class="grid gap-3 md:grid-cols-2">
          <label class="flex flex-col gap-2">
            <span class="text-xs font-medium uppercase tracking-wide opacity-70">
              Size
            </span>
            <MultiToggle
              full-width
              size="sm"
              :options="controlSizeOptions"
              :model-value="size"
              @update:model-value="size = $event as SelectSize"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span class="text-xs font-medium uppercase tracking-wide opacity-70">
              Tone
            </span>
            <Select
              :model-value="tone"
              @update:model-value="tone = $event as TrueColor"
            >
              <option
                v-for="option in trueColorOptions"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </option>
            </Select>
          </label>
        </div>

        <label class="flex flex-col gap-2">
          <span class="text-xs font-medium uppercase tracking-wide opacity-70">
            Validation
          </span>
          <MultiToggle
            full-width
            size="sm"
            :options="inputValidationOptions"
            :model-value="validationStatus"
            @update:model-value="
              validationStatus = $event as SelectValidationStatus
            "
          />
        </label>

        <div class="grid gap-2 sm:grid-cols-2 md:grid-cols-3">
          <Toggle
            v-for="toggle in stateToggles"
            :key="toggle.label"
            size="sm"
            :label="toggle.label"
            v-model="toggle.model.value"
          />
        </div>

        <p class="text-xs opacity-70">
          The surface sits on the field's wrapper, not the
          <code>&lt;select&gt;</code> — same structure as <strong>Input</strong>,
          so the caret and leading icon are flex siblings rather than absolutely
          positioned things the select has to leave padding for. The
          <code>&lt;option&gt;</code> elements carry their own fill: the native
          dropdown is painted by the platform from the select's background,
          which is now transparent.
        </p>
      </div>
    </template>

    <template #preview>
      <div class="p-4">
        <Panel
          :variant="onGlass ? 'liquid-glass' : 'outlined'"
          :tone="onGlass ? tone : 'neutral'"
          padding="md"
        >
          <div class="space-y-6">
            <div class="flex flex-col gap-2">
              <span
                class="text-[11px] font-semibold uppercase tracking-wide opacity-60"
              >
                Current settings
              </span>
              <Select
                v-model="value"
                :variant="variant"
                :size="size"
                :tone="tone"
                :validation-status="validationStatus"
                :disabled="disabled"
                :leading-icon="resolvedLeadingIcon"
                :hide-caret="hideCaret"
                :multiple="multiple"
                :placeholder="placeholder ? 'Choose a region' : undefined"
                aria-label="Region"
              >
                <option v-for="region in REGIONS" :key="region" :value="region">
                  {{ region }}
                </option>
              </Select>
            </div>

            <div class="flex flex-col gap-2">
              <span
                class="text-[11px] font-semibold uppercase tracking-wide opacity-60"
              >
                Every variant — at the same size, so they line up
              </span>
              <div class="grid gap-3 md:grid-cols-2">
                <Select
                  v-for="each in INPUT_VARIANTS"
                  :key="each"
                  :variant="each"
                  :size="size"
                  :tone="tone"
                  :validation-status="validationStatus"
                  :disabled="disabled"
                  :leading-icon="resolvedLeadingIcon"
                  :hide-caret="hideCaret"
                  :placeholder="each"
                  :aria-label="each"
                >
                  <option v-for="region in REGIONS" :key="region" :value="region">
                    {{ region }}
                  </option>
                </Select>
              </div>
            </div>

            <div class="flex flex-col gap-2">
              <span
                class="text-[11px] font-semibold uppercase tracking-wide opacity-60"
              >
                Size ladder
              </span>
              <div class="space-y-3">
                <Select
                  v-for="each in CONTROL_SIZES"
                  :key="each"
                  :variant="variant"
                  :size="each"
                  :tone="tone"
                  :validation-status="validationStatus"
                  :disabled="disabled"
                  :leading-icon="resolvedLeadingIcon"
                  :hide-caret="hideCaret"
                  :placeholder="`Size ${each}`"
                  :aria-label="`Size ${each}`"
                >
                  <option v-for="region in REGIONS" :key="region" :value="region">
                    {{ region }}
                  </option>
                </Select>
              </div>
            </div>

            <div class="flex flex-col gap-2">
              <span
                class="text-[11px] font-semibold uppercase tracking-wide opacity-60"
              >
                Validation
              </span>
              <div class="grid gap-3 md:grid-cols-3">
                <Select
                  v-for="status in (['none', 'error', 'success'] as const)"
                  :key="status"
                  :variant="variant"
                  :size="size"
                  :tone="tone"
                  :validation-status="status"
                  :leading-icon="resolvedLeadingIcon"
                  :placeholder="status"
                  :aria-label="status"
                >
                  <option v-for="region in REGIONS" :key="region" :value="region">
                    {{ region }}
                  </option>
                </Select>
              </div>
            </div>

            <div class="flex flex-col gap-2">
              <span
                class="text-[11px] font-semibold uppercase tracking-wide opacity-60"
              >
                Every tone — focus one to see its border and ring
              </span>
              <div class="grid gap-2 md:grid-cols-3 xl:grid-cols-4">
                <Select
                  v-for="each in TRUE_COLORS"
                  :key="each"
                  :variant="variant"
                  size="sm"
                  :tone="each"
                  :placeholder="each"
                  :aria-label="each"
                >
                  <option v-for="region in REGIONS" :key="region" :value="region">
                    {{ region }}
                  </option>
                </Select>
              </div>
            </div>
          </div>
        </Panel>
      </div>
    </template>
  </PlaygroundSection>
</template>

// react/demo/src/pages/UxDemo/demos/SelectDemo.tsx
import React, { useState } from "react";
import { PlaygroundSection } from "../PlaygroundSection";
import {
  MultiToggle,
  Panel,
  Select,
  Toggle,
  CONTROL_SIZES,
  INPUT_VARIANTS,
  TRUE_COLORS,
} from "@cjlapao/ui-kit";
import type {
  SelectSize,
  SelectValidationStatus,
  SelectVariant,
  TrueColor,
} from "@cjlapao/ui-kit";
import {
  controlSizeOptions,
  inputValidationOptions,
  inputVariantOptions,
  trueColorOptions,
} from "../constants";

const Field: React.FC<{ label: string; children: React.ReactNode }> = ({
  label,
  children,
}) => (
  <label className="flex flex-col gap-2">
    <span className="text-xs font-medium uppercase tracking-wide opacity-70">
      {label}
    </span>
    {children}
  </label>
);

const Caption: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <span className="text-[11px] font-semibold uppercase tracking-wide opacity-60">
    {children}
  </span>
);

const REGIONS = ["eu-west-1", "us-east-1", "ap-south-1", "sa-east-1"];

export const SelectDemo: React.FC = () => {
  const [variant, setVariant] = useState<SelectVariant>("flat");
  const [size, setSize] = useState<SelectSize>("md");
  const [tone, setTone] = useState<TrueColor>("blue");
  const [validationStatus, setValidationStatus] =
    useState<SelectValidationStatus>("none");

  const [value, setValue] = useState("");
  const [leadingIcon, setLeadingIcon] = useState(false);
  const [placeholder, setPlaceholder] = useState(true);
  const [hideCaret, setHideCaret] = useState(false);
  const [multiple, setMultiple] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [onGlass, setOnGlass] = useState(false);

  const shared = {
    variant,
    size,
    tone,
    validationStatus,
    disabled,
    leadingIcon: leadingIcon ? "Globe" : undefined,
    hideCaret,
  };

  const regionOptions = REGIONS.map((region) => (
    <option key={region} value={region}>
      {region}
    </option>
  ));

  const preview = (
    <div className="space-y-6">
      <div className="flex flex-col gap-2">
        <Caption>Current settings</Caption>
        <Select
          {...shared}
          multiple={multiple}
          placeholder={placeholder ? "Choose a region" : undefined}
          value={multiple ? undefined : value}
          onChange={(event) => setValue(event.target.value)}
          aria-label="Region"
        >
          {regionOptions}
        </Select>
      </div>

      <div className="flex flex-col gap-2">
        <Caption>Every variant — at the same size, so they line up</Caption>
        <div className="grid gap-3 md:grid-cols-2">
          {INPUT_VARIANTS.map((each) => (
            <Select
              key={each}
              {...shared}
              variant={each}
              placeholder={each}
              aria-label={each}
            >
              {regionOptions}
            </Select>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <Caption>Size ladder</Caption>
        <div className="space-y-3">
          {CONTROL_SIZES.map((each) => (
            <Select
              key={each}
              {...shared}
              size={each}
              placeholder={`Size ${each}`}
              aria-label={`Size ${each}`}
            >
              {regionOptions}
            </Select>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <Caption>Validation</Caption>
        <div className="grid gap-3 md:grid-cols-3">
          {(["none", "error", "success"] as const).map((status) => (
            <Select
              key={status}
              {...shared}
              validationStatus={status}
              placeholder={status}
              aria-label={status}
            >
              {regionOptions}
            </Select>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <Caption>Every tone — focus one to see its border and ring</Caption>
        <div className="grid gap-2 md:grid-cols-3 xl:grid-cols-4">
          {TRUE_COLORS.map((each) => (
            <Select
              key={each}
              variant={variant}
              size="sm"
              tone={each}
              placeholder={each}
              aria-label={each}
            >
              {regionOptions}
            </Select>
          ))}
        </div>
      </div>
    </div>
  );

  return (
    <PlaygroundSection
      title="Select"
      label="[Select]"
      description="The native dropdown, with the platform caret replaced by the kit's. Surface, size and tone come from the shared scales, so it lines up with the Input and SearchBar beside it."
      controls={
        <div className="space-y-5 text-sm">
          <Field label="Variant">
            <MultiToggle
              fullWidth
              size="sm"
              options={inputVariantOptions}
              value={variant}
              onChange={(value) => setVariant(value as SelectVariant)}
            />
          </Field>

          <div className="grid gap-3 md:grid-cols-2">
            <Field label="Size">
              <MultiToggle
                fullWidth
                size="sm"
                options={controlSizeOptions}
                value={size}
                onChange={(value) => setSize(value as SelectSize)}
              />
            </Field>
            <Field label="Tone">
              <Select
                value={tone}
                onChange={(event) => setTone(event.target.value as TrueColor)}
              >
                {trueColorOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </Field>
          </div>

          <Field label="Validation">
            <MultiToggle
              fullWidth
              size="sm"
              options={inputValidationOptions}
              value={validationStatus}
              onChange={(value) =>
                setValidationStatus(value as SelectValidationStatus)
              }
            />
          </Field>

          <div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">
            <Toggle
              size="sm"
              label="Leading icon"
              checked={leadingIcon}
              onChange={(event) => setLeadingIcon(event.target.checked)}
            />
            <Toggle
              size="sm"
              label="Placeholder"
              checked={placeholder}
              onChange={(event) => setPlaceholder(event.target.checked)}
            />
            <Toggle
              size="sm"
              label="Hide caret"
              checked={hideCaret}
              onChange={(event) => setHideCaret(event.target.checked)}
            />
            <Toggle
              size="sm"
              label="Multiple"
              checked={multiple}
              onChange={(event) => setMultiple(event.target.checked)}
            />
            <Toggle
              size="sm"
              label="Disabled"
              checked={disabled}
              onChange={(event) => setDisabled(event.target.checked)}
            />
            <Toggle
              size="sm"
              label="On a glass panel"
              checked={onGlass}
              onChange={(event) => setOnGlass(event.target.checked)}
            />
          </div>

          <p className="text-xs opacity-70">
            The surface sits on the field&apos;s wrapper, not the{" "}
            <code>&lt;select&gt;</code> — same structure as{" "}
            <strong>Input</strong>, so the caret and leading icon are flex
            siblings rather than absolutely positioned things the select has to
            leave padding for. The <code>&lt;option&gt;</code> elements carry
            their own fill: the native dropdown is painted by the platform from
            the select&apos;s background, which is now transparent.
          </p>
        </div>
      }
      preview={
        <div className="p-4">
          <Panel
            variant={onGlass ? "liquid-glass" : "outlined"}
            tone={onGlass ? tone : "neutral"}
            padding="md"
          >
            {preview}
          </Panel>
        </div>
      }
    />
  );
};
