// vue/demo/src/pages/UxDemo/demos/ToggleDemo.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
  Toggle,
  MultiToggle,
  type ThemeColor,
  type ToggleProps,
} from "@cjlapao/ui-kit-vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import {
  colorOptions,
  toggleSizeOptions,
  toggleAlignOptions,
  toggleDescriptionPlacementOptions,
} from "../constants";

// The individual Toggle option types are not re-exported from the kit index;
// derive them from ToggleProps.
type ToggleSize = NonNullable<ToggleProps["size"]>;
type ToggleAlign = NonNullable<ToggleProps["alignLabel"]>;
type ToggleDescriptionPlacement = NonNullable<
  ToggleProps["descriptionPlacement"]
>;

const toggleChecked = ref<boolean>(true);
const toggleColor = ref<ThemeColor>("blue");
const toggleSize = ref<ToggleSize>("md");
const toggleAlign = ref<ToggleAlign>("left");
const toggleLabel = ref<boolean>(true);
const toggleFullWidth = ref<boolean>(false);
const toggleCustomIcons = ref<boolean>(false);
const toggleDescription = ref<boolean>(false);
const toggleDisabled = ref<boolean>(false);
const toggleDescriptionPlacement = ref<ToggleDescriptionPlacement>("stacked");

const toggleBooleanOptions = computed(() => [
  {
    label: "Show label",
    value: toggleLabel.value,
    setter: (checked: boolean) => (toggleLabel.value = checked),
  },
  {
    label: "Disabled",
    value: toggleDisabled.value,
    setter: (checked: boolean) => (toggleDisabled.value = checked),
  },
  {
    label: "Show description",
    value: toggleDescription.value,
    setter: (checked: boolean) => (toggleDescription.value = checked),
  },
  {
    label: "Full width",
    value: toggleFullWidth.value,
    setter: (checked: boolean) => (toggleFullWidth.value = checked),
  },
  {
    label: "Custom icons",
    value: toggleCustomIcons.value,
    setter: (checked: boolean) => (toggleCustomIcons.value = checked),
  },
]);
</script>

<template>
  <PlaygroundSection
    title="Toggle"
    label="[Toggle]"
    description="Switch labels, layout, and icon treatments."
  >
    <template #controls>
      <div class="space-y-4">
        <div class="space-y-2">
          <span
            class="text-sm font-semibold text-neutral-600 dark:text-neutral-200"
          >
            Tone
          </span>
          <MultiToggle
            full-width
            :options="colorOptions"
            :model-value="toggleColor"
            size="sm"
            @update:model-value="
              (value: string) => (toggleColor = value as ThemeColor)
            "
          />
        </div>
        <div class="grid gap-4 md:grid-cols-2">
          <label class="flex flex-col gap-2 text-sm">
            <span>Size</span>
            <MultiToggle
              full-width
              :options="toggleSizeOptions"
              :model-value="toggleSize"
              size="sm"
              @update:model-value="
                (value: string) => (toggleSize = value as ToggleSize)
              "
            />
          </label>
          <label class="flex flex-col gap-2 text-sm">
            <span>Label alignment</span>
            <MultiToggle
              full-width
              :options="toggleAlignOptions"
              :model-value="toggleAlign"
              size="sm"
              @update:model-value="
                (value: string) => (toggleAlign = value as ToggleAlign)
              "
            />
          </label>
        </div>
        <label class="flex flex-col gap-2 text-sm">
          <span>Description placement</span>
          <MultiToggle
            full-width
            :options="toggleDescriptionPlacementOptions"
            :model-value="toggleDescriptionPlacement"
            size="sm"
            @update:model-value="
              (value: string) =>
                (toggleDescriptionPlacement =
                  value as ToggleDescriptionPlacement)
            "
          />
        </label>
        <div class="grid gap-2 text-sm md:grid-cols-2">
          <label
            v-for="option in toggleBooleanOptions"
            :key="option.label"
            class="flex items-center justify-between"
          >
            <span>{{ option.label }}</span>
            <Toggle
              size="sm"
              :model-value="option.value"
              @update:model-value="option.setter"
            />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <Toggle
        v-model="toggleChecked"
        :size="toggleSize"
        :color="toggleColor"
        :disabled="toggleDisabled"
        :label="toggleLabel ? 'Toggle Label' : undefined"
        :description="
          toggleDescription
            ? 'This is a description for the toggle component.'
            : undefined
        "
        :description-placement="toggleDescriptionPlacement"
        :align-label="toggleAlign"
        :full-width="toggleFullWidth"
        :icon-on="toggleCustomIcons ? 'Send' : undefined"
        :icon-off="toggleCustomIcons ? 'Close' : undefined"
      />
    </template>
  </PlaygroundSection>
</template>

// demo/src/pages/UxDemo/demos/ToggleDemo.tsx
// @ts-nocheck
import React, { useState } from "react";
import { PlaygroundSection } from "../PlaygroundSection";
import { Toggle, MultiToggle } from "@cjlapao/ui-kit";
import { ThemeColor } from "@cjlapao/ui-kit";
import { ToggleSize, ToggleAlign, ToggleDescriptionPlacement } from "@cjlapao/ui-kit";
import {
  colorOptions,
  toggleSizeOptions,
  toggleAlignOptions,
  toggleDescriptionPlacementOptions,
} from "../constants";

export const ToggleDemo: React.FC = () => {
  const [toggleChecked, setToggleChecked] = useState<boolean>(true);
  const [toggleColor, setToggleColor] = useState<ThemeColor>("blue");
  const [toggleSize, setToggleSize] = useState<ToggleSize>("md");
  const [toggleAlign, setToggleAlign] = useState<ToggleAlign>("left");
  const [toggleLabel, setToggleLabel] = useState<boolean>(true);
  const [toggleFullWidth, setToggleFullWidth] = useState<boolean>(false);
  const [toggleCustomIcons, setToggleCustomIcons] = useState<boolean>(false);
  const [toggleDescription, setToggleDescription] = useState<boolean>(false);
  const [toggleDisabled, setToggleDisabled] = useState<boolean>(false);
  const [toggleDescriptionPlacement, setToggleDescriptionPlacement] =
    useState<ToggleDescriptionPlacement>("stacked");

  const toggleBooleanOptions = [
    { label: "Show label", value: toggleLabel, setter: setToggleLabel },
    { label: "Disabled", value: toggleDisabled, setter: setToggleDisabled },
    {
      label: "Show description",
      value: toggleDescription,
      setter: setToggleDescription,
    },
    { label: "Full width", value: toggleFullWidth, setter: setToggleFullWidth },
    {
      label: "Custom icons",
      value: toggleCustomIcons,
      setter: setToggleCustomIcons,
    },
  ];

  return (
    <PlaygroundSection
      title="Toggle"
      label="[Toggle]"
      description="Switch labels, layout, and icon treatments."
      controls={
        <div className="space-y-4">
          <div className="space-y-2">
            <span className="text-sm font-semibold text-neutral-600 dark:text-neutral-200">
              Tone
            </span>
            <MultiToggle
              fullWidth
              options={colorOptions}
              value={toggleColor}
              size="sm"
              onChange={(value) => setToggleColor(value as ThemeColor)}
            />
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <label className="flex flex-col gap-2 text-sm">
              <span>Size</span>
              <MultiToggle
                fullWidth
                options={toggleSizeOptions}
                value={toggleSize}
                size="sm"
                onChange={(value) => setToggleSize(value as ToggleSize)}
              />
            </label>
            <label className="flex flex-col gap-2 text-sm">
              <span>Label alignment</span>
              <MultiToggle
                fullWidth
                options={toggleAlignOptions}
                value={toggleAlign}
                size="sm"
                onChange={(value) => setToggleAlign(value as ToggleAlign)}
              />
            </label>
          </div>
          <label className="flex flex-col gap-2 text-sm">
            <span>Description placement</span>
            <MultiToggle
              fullWidth
              options={toggleDescriptionPlacementOptions}
              value={toggleDescriptionPlacement}
              size="sm"
              onChange={(value) =>
                setToggleDescriptionPlacement(
                  value as ToggleDescriptionPlacement,
                )
              }
            />
          </label>
          <div className="grid gap-2 text-sm md:grid-cols-2">
            {toggleBooleanOptions.map((option) => (
              <label
                key={option.label}
                className="flex items-center justify-between"
              >
                <span>{option.label}</span>
                <Toggle
                  size="sm"
                  checked={option.value}
                  onChange={(event) => option.setter(event.target.checked)}
                />
              </label>
            ))}
          </div>
        </div>
      }
      preview={
        <Toggle
          size={toggleSize}
          color={toggleColor}
          checked={toggleChecked}
          disabled={toggleDisabled}
          label={toggleLabel ? "Toggle Label" : undefined}
          description={
            toggleDescription
              ? "This is a description for the toggle component."
              : undefined
          }
          descriptionPlacement={toggleDescriptionPlacement}
          alignLabel={toggleAlign}
          fullWidth={toggleFullWidth}
          iconOn={toggleCustomIcons ? "Send" : undefined}
          iconOff={toggleCustomIcons ? "Close" : undefined}
          onChange={(value) => setToggleChecked(value.target.checked)}
        />
      }
    />
  );
};
