// src/components/ConnectionFlow/ConnectionFlowColumn.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import classNames from "classnames";
import TreeItemCard from "../TreeView/TreeItemCard";
import TreeFlowSvg, { INDENT_PX } from "../TreeView/TreeFlowSvg";
import type { TreeTone } from "../TreeView/types";
import type { ConnectionFlowItem } from "./types";

// ── Geometry reported by a column ─────────────────────────────────────────────

export interface ColumnGeometry {
  /** Total rendered height of the whole column (parent + gap + all children). */
  totalHeight: number;
  /**
   * Y offsets (from the TOP of the column) to the centre of each source card.
   * anchors[0] = parent card, anchors[1..] = child cards (or parallel items).
   */
  anchors: number[];
  /** True when this geometry represents a parallel group (not a single-item column). */
  isParallelGroup?: boolean;
}

// ── useElementHeight ──────────────────────────────────────────────────────────

function useElementHeight(ref: React.RefObject<HTMLElement | null>): number {
  const [h, setH] = useState(0);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    let raf: number;
    const ro = new ResizeObserver(() => {
      raf = requestAnimationFrame(() => {
        if (el) setH(el.getBoundingClientRect().height);
      });
    });
    ro.observe(el);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
    };
  }, [ref]);
  return h;
}

// ── ChildRow ─────────────────────────────────────────────────────────────────

interface ChildRowProps {
  item: ConnectionFlowItem;
  index: number;
  globalTone?: TreeTone;
  hoverable?: boolean;
  onHeightChange: (h: number) => void;
  onAnchorChange: (a: number) => void;
  onToneChange: (t: TreeTone) => void;
  onActiveChange: (v: boolean) => void;
}

const ChildRow: React.FC<ChildRowProps> = ({
  item,
  index,
  globalTone,
  hoverable = false,
  onHeightChange,
  onAnchorChange,
  onToneChange,
  onActiveChange,
}) => {
  const rowRef = useRef<HTMLDivElement>(null);
  const rowH = useElementHeight(rowRef);
  const minHRef = useRef<number | null>(null);

  const resolvedTone: TreeTone = item.tone ?? globalTone ?? "neutral";
  const isActive = item.active ?? false;

  useEffect(() => {
    if (rowH > 0) {
      onHeightChange(rowH);
      if (minHRef.current === null || rowH < minHRef.current) {
        minHRef.current = rowH;
        onAnchorChange(rowH / 2);
      }
    }
  }, [rowH, onHeightChange, onAnchorChange]);

  useEffect(() => {
    onToneChange(resolvedTone);
  }, [resolvedTone, onToneChange]);
  useEffect(() => {
    onActiveChange(isActive);
  }, [isActive, onActiveChange]);

  return (
    <div ref={rowRef} className="mb-2 min-w-0">
      <TreeItemCard
        icon={item.icon}
        iconClassName={item.iconClassName}
        title={item.title}
        titleClassName={item.titleClassName}
        titleWrap={item.titleWrap}
        titleScroll={item.titleScroll}
        subtitle={item.subtitle}
        subtitleClassName={item.subtitleClassName}
        description={item.description}
        descriptionClassName={item.descriptionClassName}
        badge={item.badge}
        tone={resolvedTone}
        body={item.body}
        defaultExpanded={item.defaultExpanded}
        actions={item.actions}
        hoverActions={item.hoverActions}
        hoverable={hoverable}
        activePulse={item.activePulse}
        index={index}
      />
    </div>
  );
};

// ── ConnectionFlowColumn ──────────────────────────────────────────────────────

export interface ConnectionFlowColumnProps {
  item: ConnectionFlowItem;
  globalTone?: TreeTone;
  childIndent?: "xs" | "sm" | "md" | "lg";
  childRowGap?: number;
  animated?: boolean;
  showLine?: boolean;
  connectorHalf?: boolean;
  connectorBorderSize?: "fit" | "xs" | "sm" | "md" | "lg";
  dotSpacing?: number;
  itemWidth?: number | string;
  /** Reports geometry so ConnectionFlow can build a multi-source connector. */
  onGeometryChange?: (geo: ColumnGeometry) => void;
  /** When true, forces all child branches to animate (mirrors parent connection state). */
  flowActive?: boolean;
  /** When true, cards show a hover lift effect. */
  hoverable?: boolean;
}

// Gap between parent card bottom and first child card top (mt-2)
const CHILD_GAP_TOP = 8;
// mb-2 gap after each ChildRow
const CHILD_ROW_MB = 8;

const ConnectionFlowColumn: React.FC<ConnectionFlowColumnProps> = ({
  item,
  globalTone,
  childIndent = "xs",
  childRowGap = CHILD_ROW_MB,
  animated = true,
  showLine = true,
  connectorHalf = true,
  connectorBorderSize = "xs",
  dotSpacing = 50,
  itemWidth,
  onGeometryChange,
  flowActive = false,
  hoverable = false,
}) => {
  const hasChildren = !!(item.children && item.children.length > 0);
  const resolvedTone: TreeTone = item.tone ?? globalTone ?? "neutral";
  const childCount = item.children?.length ?? 0;

  // ── Refs & heights ────────────────────────────────────────────────────────
  const columnRef = useRef<HTMLDivElement>(null);
  const parentCardRef = useRef<HTMLDivElement>(null);
  const parentCardH = useElementHeight(parentCardRef);
  const columnH = useElementHeight(columnRef);

  // Per-child measurements
  const [cardHeights, setCardHeights] = useState<number[]>(() =>
    Array(childCount).fill(0),
  );
  const [cardAnchors, setCardAnchors] = useState<number[]>(() =>
    Array(childCount).fill(0),
  );
  const [toneList, setToneList] = useState<TreeTone[]>(() =>
    Array(childCount).fill(globalTone ?? "neutral"),
  );
  const [activeList, setActiveList] = useState<boolean[]>(() =>
    Array(childCount).fill(false),
  );

  // Reset arrays when child count changes
  useEffect(() => {
    setCardHeights(Array(childCount).fill(0));
    setCardAnchors(Array(childCount).fill(0));
    setToneList(Array(childCount).fill(globalTone ?? "neutral"));
    setActiveList(Array(childCount).fill(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [childCount]);

  const updH = useCallback(
    (i: number, h: number) =>
      setCardHeights((p) => {
        if (p[i] === h) return p;
        const n = [...p];
        n[i] = h;
        return n;
      }),
    [],
  );
  const updA = useCallback(
    (i: number, a: number) =>
      setCardAnchors((p) => {
        if (p[i] === a) return p;
        const n = [...p];
        n[i] = a;
        return n;
      }),
    [],
  );
  const updT = useCallback(
    (i: number, t: TreeTone) =>
      setToneList((p) => {
        if (p[i] === t) return p;
        const n = [...p];
        n[i] = t;
        return n;
      }),
    [],
  );
  const updAc = useCallback(
    (i: number, v: boolean) =>
      setActiveList((p) => {
        if (p[i] === v) return p;
        const n = [...p];
        n[i] = v;
        return n;
      }),
    [],
  );

  // ── Geometry → ConnectionFlow ─────────────────────────────────────────────
  useEffect(() => {
    if (!onGeometryChange || parentCardH === 0 || columnH === 0) return;

    const anchors: number[] = [parentCardH / 2];

    if (
      hasChildren &&
      cardHeights.length > 0 &&
      cardHeights.every((h) => h > 0)
    ) {
      // Children start after: parentCard + mt-2 (CHILD_GAP_TOP)
      const childBlockTop = parentCardH + CHILD_GAP_TOP;
      let rowTop = childBlockTop;
      cardHeights.forEach((h, idx) => {
        anchors.push(rowTop + (cardAnchors[idx] ?? h / 2));
        rowTop += h + childRowGap;
      });
    }

    onGeometryChange({ totalHeight: columnH, anchors });
  }, [
    parentCardH,
    columnH,
    cardHeights,
    cardAnchors,
    hasChildren,
    childRowGap,
    onGeometryChange,
  ]);

  // Force-active merging for TreeFlowSvg
  const mergedActiveList = flowActive ? activeList.map(() => true) : activeList;

  return (
    <div
      ref={columnRef}
      className={classNames(
        "flex flex-col relative",
        itemWidth ? "shrink-0" : "flex-1 min-w-0",
      )}
      style={itemWidth ? { width: itemWidth } : undefined}
    >
      {/* Parent card — full width */}
      <div ref={parentCardRef}>
        <TreeItemCard
          icon={item.icon}
          iconClassName={item.iconClassName}
          title={item.title}
          titleClassName={item.titleClassName}
          titleWrap={item.titleWrap}
          titleScroll={item.titleScroll}
          subtitle={item.subtitle}
          subtitleClassName={item.subtitleClassName}
          description={item.description}
          descriptionClassName={item.descriptionClassName}
          badge={item.badge}
          tone={resolvedTone}
          body={item.body}
          defaultExpanded={item.defaultExpanded}
          actions={item.actions}
          hoverActions={item.hoverActions}
          hoverable={hoverable}
          activePulse={item.activePulse}
        />
      </div>

      {/* Children — full width, NO paddingLeft */}
      {hasChildren && (
        <div className="mt-2 flex-1">
          {item.children!.map((child, i) => (
            <ChildRow
              key={child.id}
              item={child}
              index={i}
              globalTone={globalTone}
              hoverable={hoverable}
              onHeightChange={(h) => updH(i, h)}
              onAnchorChange={(a) => updA(i, a)}
              onToneChange={(t) => updT(i, t)}
              onActiveChange={(v) => updAc(i, v)}
            />
          ))}
        </div>
      )}

      {/* Column-level SVG: positioned to the left of the column
                and draws the [ shape connecting parent left edge to children's left edges */}
      {hasChildren && parentCardH > 0 && cardHeights.every((h) => h > 0) && (
        <TreeFlowSvg
          mode="bracket"
          parentAnchorY={parentCardH - 16}
          cardHeights={cardHeights}
          cardAnchors={cardAnchors}
          toneList={toneList}
          activeList={mergedActiveList}
          rootTone={resolvedTone}
          rootActive={item.active || flowActive}
          rowGap={childRowGap}
          stubHeight={parentCardH + CHILD_GAP_TOP}
          indent={childIndent}
          showLine={showLine}
          showConnectors
          connectorHalf={connectorHalf}
          connectorBorderSize={connectorBorderSize}
          dotSpacing={dotSpacing}
          animated={animated}
          style={{
            position: "absolute",
            left: -INDENT_PX[childIndent],
            top: 0,
            pointerEvents: "none",
          }}
        />
      )}
    </div>
  );
};

export default ConnectionFlowColumn;

// vue/src/components/ConnectionFlow/ConnectionFlowColumn.vue
<script lang="ts">
import { ref, watch, type Ref } from "vue";
import type { TreeTone } from "../TreeView/types";
import type { ConnectionFlowItem } from "./types";

// ── Geometry reported by a column ─────────────────────────────────────────────

export interface ColumnGeometry {
  /** Total rendered height of the whole column (parent + gap + all children). */
  totalHeight: number;
  /**
   * Y offsets (from the TOP of the column) to the centre of each source card.
   * anchors[0] = parent card, anchors[1..] = child cards (or parallel items).
   */
  anchors: number[];
  /** True when this geometry represents a parallel group (not a single-item column). */
  isParallelGroup?: boolean;
}

// ── useElementHeight ──────────────────────────────────────────────────────────

function useElementHeight(elRef: Ref<HTMLElement | null>): Ref<number> {
  const h = ref(0);
  watch(
    elRef,
    (el, _prev, onCleanup) => {
      if (!el) return;
      let raf = 0;
      const ro = new ResizeObserver(() => {
        raf = requestAnimationFrame(() => {
          if (el) h.value = el.getBoundingClientRect().height;
        });
      });
      ro.observe(el);
      onCleanup(() => {
        cancelAnimationFrame(raf);
        ro.disconnect();
      });
    },
    { immediate: true, flush: "post" },
  );
  return h;
}

// ── ConnectionFlowColumn ──────────────────────────────────────────────────────

export interface ConnectionFlowColumnProps {
  item: ConnectionFlowItem;
  globalTone?: TreeTone;
  childIndent?: "xs" | "sm" | "md" | "lg";
  childRowGap?: number;
  animated?: boolean;
  showLine?: boolean;
  connectorHalf?: boolean;
  connectorBorderSize?: "fit" | "xs" | "sm" | "md" | "lg";
  dotSpacing?: number;
  itemWidth?: number | string;
  /** When true, forces all child branches to animate (mirrors parent connection state). */
  flowActive?: boolean;
  /** When true, cards show a hover lift effect. */
  hoverable?: boolean;
}

// Gap between parent card bottom and first child card top (mt-2)
const CHILD_GAP_TOP = 8;
// mb-2 gap after each ChildRow
const CHILD_ROW_MB = 8;
</script>

<script setup lang="ts">
import { computed, shallowRef, type CSSProperties } from "vue";
import classNames from "classnames";
import TreeItemCard from "../TreeView/TreeItemCard.vue";
import TreeFlowSvg, { INDENT_PX } from "../TreeView/TreeFlowSvg.vue";

defineOptions({ name: "ConnectionFlowColumn" });

const props = withDefaults(defineProps<ConnectionFlowColumnProps>(), {
  childIndent: "xs",
  childRowGap: CHILD_ROW_MB,
  animated: true,
  showLine: true,
  connectorHalf: true,
  connectorBorderSize: "xs",
  dotSpacing: 50,
  flowActive: false,
  hoverable: false,
});

const emit = defineEmits<{
  /** Reports geometry so ConnectionFlow can build a multi-source connector. */
  (e: "geometryChange", geo: ColumnGeometry): void;
}>();

const hasChildren = computed(
  () => !!(props.item.children && props.item.children.length > 0),
);
const resolvedTone = computed<TreeTone>(
  () => props.item.tone ?? props.globalTone ?? "neutral",
);
const childCount = computed(() => props.item.children?.length ?? 0);

// ── Refs & heights ────────────────────────────────────────────────────────
const columnRef = ref<HTMLDivElement | null>(null);
const parentCardRef = ref<HTMLDivElement | null>(null);
const parentCardH = useElementHeight(parentCardRef);
const columnH = useElementHeight(columnRef);

// Per-child measurements
const childEls = shallowRef<(HTMLElement | null)[]>([]);
const cardHeights = ref<number[]>(Array(childCount.value).fill(0));
const cardAnchors = ref<number[]>(Array(childCount.value).fill(0));
// Minimum height seen per child — the anchor tracks the collapsed card centre
const minChildHeights: (number | null)[] = [];

const setChildEl = (i: number, el: HTMLElement | null) => {
  if (childEls.value[i] !== el) {
    const next = childEls.value.slice();
    next[i] = el;
    childEls.value = next;
  }
};

// Reset arrays when child count changes
watch(childCount, (n) => {
  cardHeights.value = Array(n).fill(0);
  cardAnchors.value = Array(n).fill(0);
  minChildHeights.length = 0;
  childEls.value = childEls.value.slice(0, n);
});

const updH = (i: number, h: number) => {
  if (cardHeights.value[i] === h) return;
  const n = [...cardHeights.value];
  n[i] = h;
  cardHeights.value = n;
};
const updA = (i: number, a: number) => {
  if (cardAnchors.value[i] === a) return;
  const n = [...cardAnchors.value];
  n[i] = a;
  cardAnchors.value = n;
};

// Register a ResizeObserver per child row (mirrors React's ChildRow refs)
watch(
  childEls,
  (els, _prev, onCleanup) => {
    const observers: ResizeObserver[] = [];
    const rafs: number[] = [];
    els.forEach((el, i) => {
      if (!el) return;
      const ro = new ResizeObserver(() => {
        const raf = requestAnimationFrame(() => {
          if (!el) return;
          const h = el.getBoundingClientRect().height;
          if (h > 0) {
            updH(i, h);
            const minH = minChildHeights[i];
            if (minH === null || minH === undefined || h < minH) {
              minChildHeights[i] = h;
              updA(i, h / 2);
            }
          }
        });
        rafs.push(raf);
      });
      ro.observe(el);
      observers.push(ro);
    });
    onCleanup(() => {
      rafs.forEach(cancelAnimationFrame);
      observers.forEach((ro) => ro.disconnect());
    });
  },
  { immediate: true, flush: "post" },
);

// Tone/active per child — derived directly from item data (mirrors ChildRow reports)
const toneList = computed<TreeTone[]>(() =>
  (props.item.children ?? []).map(
    (child) => child.tone ?? props.globalTone ?? "neutral",
  ),
);
const activeList = computed<boolean[]>(() =>
  (props.item.children ?? []).map((child) => child.active ?? false),
);

// ── Geometry → ConnectionFlow ─────────────────────────────────────────────
watch(
  [parentCardH, columnH, cardHeights, cardAnchors, hasChildren, () => props.childRowGap],
  () => {
    if (parentCardH.value === 0 || columnH.value === 0) return;

    const anchors: number[] = [parentCardH.value / 2];

    if (
      hasChildren.value &&
      cardHeights.value.length > 0 &&
      cardHeights.value.every((h) => h > 0)
    ) {
      // Children start after: parentCard + mt-2 (CHILD_GAP_TOP)
      const childBlockTop = parentCardH.value + CHILD_GAP_TOP;
      let rowTop = childBlockTop;
      cardHeights.value.forEach((h, idx) => {
        anchors.push(rowTop + (cardAnchors.value[idx] ?? h / 2));
        rowTop += h + props.childRowGap;
      });
    }

    emit("geometryChange", { totalHeight: columnH.value, anchors });
  },
);

// Force-active merging for TreeFlowSvg
const mergedActiveList = computed(() =>
  props.flowActive ? activeList.value.map(() => true) : activeList.value,
);

const rootClass = computed(() =>
  classNames(
    "flex flex-col relative",
    props.itemWidth ? "shrink-0" : "flex-1 min-w-0",
  ),
);
const rootStyle = computed<CSSProperties | undefined>(() =>
  props.itemWidth
    ? {
        width:
          typeof props.itemWidth === "number"
            ? `${props.itemWidth}px`
            : props.itemWidth,
      }
    : undefined,
);

const showTreeSvg = computed(
  () =>
    hasChildren.value &&
    parentCardH.value > 0 &&
    cardHeights.value.every((h) => h > 0),
);

// Column-level SVG: positioned to the left of the column
// and draws the [ shape connecting parent left edge to children's left edges
const treeSvgStyle = computed<CSSProperties>(() => ({
  position: "absolute",
  left: `${-INDENT_PX[props.childIndent]}px`,
  top: "0",
  pointerEvents: "none",
}));
</script>

<template>
  <div ref="columnRef" :class="rootClass" :style="rootStyle">
    <!-- Parent card — full width -->
    <div ref="parentCardRef">
      <TreeItemCard
        :icon="item.icon"
        :icon-class-name="item.iconClassName"
        :title="item.title"
        :title-class-name="item.titleClassName"
        :title-wrap="item.titleWrap"
        :title-scroll="item.titleScroll"
        :subtitle="item.subtitle"
        :subtitle-class-name="item.subtitleClassName"
        :description="item.description"
        :description-class-name="item.descriptionClassName"
        :badge="item.badge"
        :tone="resolvedTone"
        :body="item.body"
        :default-expanded="item.defaultExpanded"
        :actions="item.actions"
        :hover-actions="item.hoverActions"
        :hoverable="hoverable"
        :active-pulse="item.activePulse"
      />
    </div>

    <!-- Children — full width, NO paddingLeft -->
    <div v-if="hasChildren" class="mt-2 flex-1">
      <div
        v-for="(child, i) in item.children"
        :key="child.id"
        :ref="(el: unknown) => setChildEl(i, el as HTMLElement | null)"
        class="mb-2 min-w-0"
      >
        <TreeItemCard
          :icon="child.icon"
          :icon-class-name="child.iconClassName"
          :title="child.title"
          :title-class-name="child.titleClassName"
          :title-wrap="child.titleWrap"
          :title-scroll="child.titleScroll"
          :subtitle="child.subtitle"
          :subtitle-class-name="child.subtitleClassName"
          :description="child.description"
          :description-class-name="child.descriptionClassName"
          :badge="child.badge"
          :tone="child.tone ?? globalTone ?? 'neutral'"
          :body="child.body"
          :default-expanded="child.defaultExpanded"
          :actions="child.actions"
          :hover-actions="child.hoverActions"
          :hoverable="hoverable"
          :active-pulse="child.activePulse"
          :index="i"
        />
      </div>
    </div>

    <!-- Column-level SVG: positioned to the left of the column
                and draws the [ shape connecting parent left edge to children's left edges -->
    <TreeFlowSvg
      v-if="showTreeSvg"
      mode="bracket"
      :parent-anchor-y="parentCardH - 16"
      :card-heights="cardHeights"
      :card-anchors="cardAnchors"
      :tone-list="toneList"
      :active-list="mergedActiveList"
      :root-tone="resolvedTone"
      :root-active="item.active || flowActive"
      :row-gap="childRowGap"
      :stub-height="parentCardH + CHILD_GAP_TOP"
      :indent="childIndent"
      :show-line="showLine"
      show-connectors
      :connector-half="connectorHalf"
      :connector-border-size="connectorBorderSize"
      :dot-spacing="dotSpacing"
      :animated="animated"
      :style="treeSvgStyle"
    />
  </div>
</template>
