// vue/src/components/PasswordInput.vue
<script lang="ts">
import type { InputProps } from "./Input.vue";

export type PasswordInputProps = Omit<
  InputProps,
  "trailingIcon" | "onTrailingIconClick"
>;
</script>

<script setup lang="ts">
import { computed, h, ref } from "vue";
import Input from "./Input.vue";
import { EyeOpen } from "../icons/components/EyeOpen";
import { EyeClosed } from "../icons/components/EyeClosed";

defineOptions({ name: "PasswordInput", inheritAttrs: false });

const showPassword = ref(false);

const inputRef = ref<InstanceType<typeof Input> | null>(null);
const el = computed(() => inputRef.value?.el ?? null);
defineExpose({ el });

const trailingIcon = computed(() =>
  showPassword.value
    ? h(EyeClosed, { class: "w-4 h-4" })
    : h(EyeOpen, { class: "w-4 h-4" }),
);

const toggleShowPassword = () => {
  showPassword.value = !showPassword.value;
};
</script>

<template>
  <Input
    ref="inputRef"
    v-bind="$attrs"
    :type="showPassword ? 'text' : 'password'"
    :trailing-icon="trailingIcon"
    :on-trailing-icon-click="toggleShowPassword"
    :trailing-icon-label="showPassword ? 'Hide password' : 'Show password'"
  />
</template>

// react/src/components/PasswordInput.tsx
import { useState, forwardRef, type ForwardedRef } from "react";
import Input, { type InputProps } from "./Input";
import { EyeOpen } from "../icons/components/EyeOpen";
import { EyeClosed } from "../icons/components/EyeClosed";

export type PasswordInputProps = Omit<
  InputProps,
  "type" | "trailingIcon" | "onTrailingIconClick"
>;

const PasswordInput = forwardRef<HTMLInputElement, PasswordInputProps>(
  function PasswordInput(props, ref: ForwardedRef<HTMLInputElement>) {
    const [showPassword, setShowPassword] = useState(false);

    return (
      <Input
        {...props}
        ref={ref}
        type={showPassword ? "text" : "password"}
        trailingIcon={
          showPassword ? (
            <EyeClosed className="w-4 h-4" />
          ) : (
            <EyeOpen className="w-4 h-4" />
          )
        }
        onTrailingIconClick={() => setShowPassword((v) => !v)}
        trailingIconLabel={showPassword ? "Hide password" : "Show password"}
      />
    );
  },
);

PasswordInput.displayName = "PasswordInput";

export default PasswordInput;
