// react/demo/src/pages/UxDemo/demos/AccessMatrixDemo.tsx
import React, { useState } from "react";
import { PlaygroundSection } from "../PlaygroundSection";
import { AccessMatrix, MultiToggle, Toggle, Select } from "@cjlapao/ui-kit";
import type {
  AccessMatrixPermission,
  TableVariant,
  TableDensity,
  SurfaceCorner,
  PanelTone,
} from "@cjlapao/ui-kit";
import {
  tableVariantOptions,
  tableDensityOptions,
  surfaceCornerOptions,
  trueColorOptions,
} from "../constants";

const SAMPLE_PERMISSIONS: AccessMatrixPermission[] = [
  // Administrators — full access
  { group: "Administrators", resource: "VMs", action: "View", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Create", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Edit", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Delete", enabled: true },
  { group: "Administrators", resource: "Users", action: "View", enabled: true },
  {
    group: "Administrators",
    resource: "Users",
    action: "Create",
    enabled: true,
  },
  { group: "Administrators", resource: "Users", action: "Edit", enabled: true },
  {
    group: "Administrators",
    resource: "Users",
    action: "Delete",
    enabled: true,
  },
  { group: "Administrators", resource: "Logs", action: "View", enabled: true },
  {
    group: "Administrators",
    resource: "Logs",
    action: "Export",
    enabled: true,
  },

  // Power Users — manage VMs, view users, view logs
  { group: "Power Users", resource: "VMs", action: "View", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Create", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Edit", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Delete", enabled: false },
  { group: "Power Users", resource: "Users", action: "View", enabled: true },
  { group: "Power Users", resource: "Users", action: "Create", enabled: false },
  { group: "Power Users", resource: "Users", action: "Edit", enabled: false },
  { group: "Power Users", resource: "Users", action: "Delete", enabled: false },
  { group: "Power Users", resource: "Logs", action: "View", enabled: true },
  { group: "Power Users", resource: "Logs", action: "Export", enabled: true },

  // Developers — view VMs, no user management
  { group: "Developers", resource: "VMs", action: "View", enabled: true },
  { group: "Developers", resource: "VMs", action: "Create", enabled: false },
  { group: "Developers", resource: "VMs", action: "Edit", enabled: true },
  { group: "Developers", resource: "VMs", action: "Delete", enabled: false },
  { group: "Developers", resource: "Users", action: "View", enabled: false },
  { group: "Developers", resource: "Users", action: "Create", enabled: false },
  { group: "Developers", resource: "Users", action: "Edit", enabled: false },
  { group: "Developers", resource: "Users", action: "Delete", enabled: false },
  { group: "Developers", resource: "Logs", action: "View", enabled: true },
  { group: "Developers", resource: "Logs", action: "Export", enabled: false },

  // Read Only — view everything, change nothing
  { group: "Read Only", resource: "VMs", action: "View", enabled: true },
  { group: "Read Only", resource: "VMs", action: "Create", enabled: false },
  { group: "Read Only", resource: "VMs", action: "Edit", enabled: false },
  { group: "Read Only", resource: "VMs", action: "Delete", enabled: false },
  { group: "Read Only", resource: "Users", action: "View", enabled: true },
  { group: "Read Only", resource: "Users", action: "Create", enabled: false },
  { group: "Read Only", resource: "Users", action: "Edit", enabled: false },
  { group: "Read Only", resource: "Users", action: "Delete", enabled: false },
  { group: "Read Only", resource: "Logs", action: "View", enabled: true },
  { group: "Read Only", resource: "Logs", action: "Export", enabled: false },

  // Support — view VMs and logs only
  { group: "Support", resource: "VMs", action: "View", enabled: true },
  { group: "Support", resource: "VMs", action: "Create", enabled: false },
  { group: "Support", resource: "VMs", action: "Edit", enabled: false },
  { group: "Support", resource: "VMs", action: "Delete", enabled: false },
  { group: "Support", resource: "Users", action: "View", enabled: false },
  { group: "Support", resource: "Users", action: "Create", enabled: false },
  { group: "Support", resource: "Users", action: "Edit", enabled: false },
  { group: "Support", resource: "Users", action: "Delete", enabled: false },
  { group: "Support", resource: "Logs", action: "View", enabled: true },
  { group: "Support", resource: "Logs", action: "Export", enabled: false },

  // Auditors — logs only, full access
  { group: "Auditors", resource: "VMs", action: "View", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Create", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Edit", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Delete", enabled: false },
  { group: "Auditors", resource: "Users", action: "View", enabled: false },
  { group: "Auditors", resource: "Users", action: "Create", enabled: false },
  { group: "Auditors", resource: "Users", action: "Edit", enabled: false },
  { group: "Auditors", resource: "Users", action: "Delete", enabled: false },
  { group: "Auditors", resource: "Logs", action: "View", enabled: true },
  { group: "Auditors", resource: "Logs", action: "Export", enabled: true },

  // Guests — no permissions
  { group: "Guests", resource: "VMs", action: "View", enabled: false },
  { group: "Guests", resource: "VMs", action: "Create", enabled: false },
  { group: "Guests", resource: "VMs", action: "Edit", enabled: false },
  { group: "Guests", resource: "VMs", action: "Delete", enabled: false },
  { group: "Guests", resource: "Users", action: "View", enabled: false },
  { group: "Guests", resource: "Users", action: "Create", enabled: false },
  { group: "Guests", resource: "Users", action: "Edit", enabled: false },
  { group: "Guests", resource: "Users", action: "Delete", enabled: false },
  { group: "Guests", resource: "Logs", action: "View", enabled: false },
  { group: "Guests", resource: "Logs", action: "Export", enabled: false },
];

export const AccessMatrixDemo: React.FC = () => {
  const [variant, setVariant] = useState<TableVariant>("default");
  const [density, setDensity] = useState<TableDensity>("default");
  const [corner, setCorner] = useState<SurfaceCorner>("rounded-md");
  const [tone, setTone] = useState<PanelTone>("neutral");
  const [limit, setLimit] = useState<number>(4);
  const [striped, setStriped] = useState(true);
  const [bordered, setBordered] = useState(false);
  const [hoverable, setHoverable] = useState(false);

  return (
    <PlaygroundSection
      title="Access Matrix"
      label="[AccessMatrix]"
      description="Read-only permission matrix showing group access across resources and actions."
      controls={
        <div className="space-y-4 text-sm">
          <label className="flex flex-col gap-2">
            <span>Variant</span>
            <MultiToggle
              fullWidth
              options={tableVariantOptions}
              value={variant}
              size="sm"
              onChange={(value) => setVariant(value as TableVariant)}
            />
          </label>
          <label className="flex flex-col gap-2">
            <span>Density</span>
            <MultiToggle
              fullWidth
              options={tableDensityOptions}
              value={density}
              size="sm"
              onChange={(value) => setDensity(value as TableDensity)}
            />
          </label>
          <label className="flex flex-col gap-2">
            <span>Corner</span>
            <MultiToggle
              fullWidth
              options={surfaceCornerOptions}
              value={corner}
              size="sm"
              onChange={(value) => setCorner(value as SurfaceCorner)}
            />
          </label>
          <label className="flex flex-col gap-2">
            <span>Tone</span>
            <Select
              value={tone}
              onChange={(event) => setTone(event.target.value as PanelTone)}
            >
              {trueColorOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </Select>
          </label>
          <label className="flex flex-col gap-2">
            <span>Row limit (before expand)</span>
            <MultiToggle
              fullWidth
              options={[
                { label: "3", value: "3" },
                { label: "4", value: "4" },
                { label: "5", value: "5" },
              ]}
              value={String(limit)}
              size="sm"
              onChange={(value) => setLimit(Number(value))}
            />
          </label>
          <div className="grid gap-2 md:grid-cols-2">
            <label className="flex items-center justify-between">
              <span>Striped rows</span>
              <Toggle
                size="sm"
                checked={striped}
                onChange={(e) => setStriped(e.target.checked)}
              />
            </label>
            <label className="flex items-center justify-between">
              <span>Bordered grid</span>
              <Toggle
                size="sm"
                checked={bordered}
                onChange={(e) => setBordered(e.target.checked)}
              />
            </label>
            <label className="flex items-center justify-between">
              <span>Hover state</span>
              <Toggle
                size="sm"
                checked={hoverable}
                onChange={(e) => setHoverable(e.target.checked)}
              />
            </label>
          </div>
        </div>
      }
      preview={
        <AccessMatrix
          permissions={SAMPLE_PERMISSIONS}
          limit={limit}
          variant={variant}
          density={density}
          corner={corner}
          tone={tone}
          bordered={bordered}
          striped={striped}
          hoverable={hoverable}
        />
      }
    />
  );
};

// vue/demo/src/pages/UxDemo/demos/AccessMatrixDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import { AccessMatrix, MultiToggle, Toggle, Select } from "@cjlapao/ui-kit-vue";
import type {
  AccessMatrixPermission,
  TableVariant,
  TableDensity,
  SurfaceCorner,
  PanelTone,
} from "@cjlapao/ui-kit-vue";
import {
  tableVariantOptions,
  tableDensityOptions,
  surfaceCornerOptions,
  trueColorOptions,
} from "../constants";

const SAMPLE_PERMISSIONS: AccessMatrixPermission[] = [
  // Administrators — full access
  { group: "Administrators", resource: "VMs", action: "View", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Create", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Edit", enabled: true },
  { group: "Administrators", resource: "VMs", action: "Delete", enabled: true },
  { group: "Administrators", resource: "Users", action: "View", enabled: true },
  {
    group: "Administrators",
    resource: "Users",
    action: "Create",
    enabled: true,
  },
  { group: "Administrators", resource: "Users", action: "Edit", enabled: true },
  {
    group: "Administrators",
    resource: "Users",
    action: "Delete",
    enabled: true,
  },
  { group: "Administrators", resource: "Logs", action: "View", enabled: true },
  {
    group: "Administrators",
    resource: "Logs",
    action: "Export",
    enabled: true,
  },

  // Power Users — manage VMs, view users, view logs
  { group: "Power Users", resource: "VMs", action: "View", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Create", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Edit", enabled: true },
  { group: "Power Users", resource: "VMs", action: "Delete", enabled: false },
  { group: "Power Users", resource: "Users", action: "View", enabled: true },
  { group: "Power Users", resource: "Users", action: "Create", enabled: false },
  { group: "Power Users", resource: "Users", action: "Edit", enabled: false },
  { group: "Power Users", resource: "Users", action: "Delete", enabled: false },
  { group: "Power Users", resource: "Logs", action: "View", enabled: true },
  { group: "Power Users", resource: "Logs", action: "Export", enabled: true },

  // Developers — view VMs, no user management
  { group: "Developers", resource: "VMs", action: "View", enabled: true },
  { group: "Developers", resource: "VMs", action: "Create", enabled: false },
  { group: "Developers", resource: "VMs", action: "Edit", enabled: true },
  { group: "Developers", resource: "VMs", action: "Delete", enabled: false },
  { group: "Developers", resource: "Users", action: "View", enabled: false },
  { group: "Developers", resource: "Users", action: "Create", enabled: false },
  { group: "Developers", resource: "Users", action: "Edit", enabled: false },
  { group: "Developers", resource: "Users", action: "Delete", enabled: false },
  { group: "Developers", resource: "Logs", action: "View", enabled: true },
  { group: "Developers", resource: "Logs", action: "Export", enabled: false },

  // Read Only — view everything, change nothing
  { group: "Read Only", resource: "VMs", action: "View", enabled: true },
  { group: "Read Only", resource: "VMs", action: "Create", enabled: false },
  { group: "Read Only", resource: "VMs", action: "Edit", enabled: false },
  { group: "Read Only", resource: "VMs", action: "Delete", enabled: false },
  { group: "Read Only", resource: "Users", action: "View", enabled: true },
  { group: "Read Only", resource: "Users", action: "Create", enabled: false },
  { group: "Read Only", resource: "Users", action: "Edit", enabled: false },
  { group: "Read Only", resource: "Users", action: "Delete", enabled: false },
  { group: "Read Only", resource: "Logs", action: "View", enabled: true },
  { group: "Read Only", resource: "Logs", action: "Export", enabled: false },

  // Support — view VMs and logs only
  { group: "Support", resource: "VMs", action: "View", enabled: true },
  { group: "Support", resource: "VMs", action: "Create", enabled: false },
  { group: "Support", resource: "VMs", action: "Edit", enabled: false },
  { group: "Support", resource: "VMs", action: "Delete", enabled: false },
  { group: "Support", resource: "Users", action: "View", enabled: false },
  { group: "Support", resource: "Users", action: "Create", enabled: false },
  { group: "Support", resource: "Users", action: "Edit", enabled: false },
  { group: "Support", resource: "Users", action: "Delete", enabled: false },
  { group: "Support", resource: "Logs", action: "View", enabled: true },
  { group: "Support", resource: "Logs", action: "Export", enabled: false },

  // Auditors — logs only, full access
  { group: "Auditors", resource: "VMs", action: "View", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Create", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Edit", enabled: false },
  { group: "Auditors", resource: "VMs", action: "Delete", enabled: false },
  { group: "Auditors", resource: "Users", action: "View", enabled: false },
  { group: "Auditors", resource: "Users", action: "Create", enabled: false },
  { group: "Auditors", resource: "Users", action: "Edit", enabled: false },
  { group: "Auditors", resource: "Users", action: "Delete", enabled: false },
  { group: "Auditors", resource: "Logs", action: "View", enabled: true },
  { group: "Auditors", resource: "Logs", action: "Export", enabled: true },

  // Guests — no permissions
  { group: "Guests", resource: "VMs", action: "View", enabled: false },
  { group: "Guests", resource: "VMs", action: "Create", enabled: false },
  { group: "Guests", resource: "VMs", action: "Edit", enabled: false },
  { group: "Guests", resource: "VMs", action: "Delete", enabled: false },
  { group: "Guests", resource: "Users", action: "View", enabled: false },
  { group: "Guests", resource: "Users", action: "Create", enabled: false },
  { group: "Guests", resource: "Users", action: "Edit", enabled: false },
  { group: "Guests", resource: "Users", action: "Delete", enabled: false },
  { group: "Guests", resource: "Logs", action: "View", enabled: false },
  { group: "Guests", resource: "Logs", action: "Export", enabled: false },
];

const limitOptions = [
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
];

const variant = ref<TableVariant>("default");
const density = ref<TableDensity>("default");
const corner = ref<SurfaceCorner>("rounded-md");
const tone = ref<PanelTone>("neutral");
const limit = ref<number>(4);
const striped = ref(true);
const bordered = ref(false);
const hoverable = ref(false);
</script>

<template>
  <PlaygroundSection
    title="Access Matrix"
    label="[AccessMatrix]"
    description="Read-only permission matrix showing group access across resources and actions."
  >
    <template #controls>
      <div class="space-y-4 text-sm">
        <label class="flex flex-col gap-2">
          <span>Variant</span>
          <MultiToggle
            full-width
            :options="tableVariantOptions"
            :model-value="variant"
            size="sm"
            @update:model-value="variant = $event as TableVariant"
          />
        </label>
        <label class="flex flex-col gap-2">
          <span>Density</span>
          <MultiToggle
            full-width
            :options="tableDensityOptions"
            :model-value="density"
            size="sm"
            @update:model-value="density = $event as TableDensity"
          />
        </label>
        <label class="flex flex-col gap-2">
          <span>Corner</span>
          <MultiToggle
            full-width
            :options="surfaceCornerOptions"
            :model-value="corner"
            size="sm"
            @update:model-value="corner = $event as SurfaceCorner"
          />
        </label>
        <label class="flex flex-col gap-2">
          <span>Tone</span>
          <Select
            :model-value="tone"
            @update:model-value="tone = $event as PanelTone"
          >
            <option
              v-for="option in trueColorOptions"
              :key="option.value"
              :value="option.value"
            >
              {{ option.label }}
            </option>
          </Select>
        </label>
        <label class="flex flex-col gap-2">
          <span>Row limit (before expand)</span>
          <MultiToggle
            full-width
            :options="limitOptions"
            :model-value="String(limit)"
            size="sm"
            @update:model-value="limit = Number($event)"
          />
        </label>
        <div class="grid gap-2 md:grid-cols-2">
          <label class="flex items-center justify-between">
            <span>Striped rows</span>
            <Toggle size="sm" v-model="striped" />
          </label>
          <label class="flex items-center justify-between">
            <span>Bordered grid</span>
            <Toggle size="sm" v-model="bordered" />
          </label>
          <label class="flex items-center justify-between">
            <span>Hover state</span>
            <Toggle size="sm" v-model="hoverable" />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <AccessMatrix
        :permissions="SAMPLE_PERMISSIONS"
        :limit="limit"
        :variant="variant"
        :density="density"
        :corner="corner"
        :tone="tone"
        :bordered="bordered"
        :striped="striped"
        :hoverable="hoverable"
      />
    </template>
  </PlaygroundSection>
</template>
