// demo/src/pages/UxDemo/demos/EmptyStateDemo.tsx
// @ts-nocheck
import React, { useState } from "react";
import {
  EmptyState,
  type EmptyStateProps,
  MultiToggle,
  Toggle,
  type ButtonVariant,
  type ButtonColor,
  type ButtonSize,
} from "@cjlapao/ui-kit";
import type { IconName } from "@cjlapao/ui-kit";

type EmptyStateTone = EmptyStateProps["tone"];
import { PlaygroundSection } from "../PlaygroundSection";
import {
  alertToneOptions,
  buttonVariantOptions,
  colorOptions,
  buttonSizeOptions,
} from "../constants";

export const EmptyStateDemo: React.FC = () => {
  const [emptyTone, setEmptyTone] = useState<EmptyStateTone>("neutral");
  const [emptyTitle, setEmptyTitle] = useState("All caught up");
  const [emptySubtitle, setEmptySubtitle] = useState(
    "Connect your first workspace or import data to see activity here.",
  );
  const [emptyShowSubtitle, setEmptyShowSubtitle] = useState(true);
  const [emptyShowIcon, setEmptyShowIcon] = useState(true);
  const [emptyShowAction, setEmptyShowAction] = useState(true);
  const [emptyButtonText, setEmptyButtonText] = useState("Create workspace");
  const [emptyActionVariant, setEmptyActionVariant] =
    useState<ButtonVariant>("soft");
  const [emptyActionColor, setEmptyActionColor] = useState<ButtonColor>("blue");
  const [emptyFullWidth, setEmptyFullWidth] = useState(false);
  const [emptyActionSize, setEmptyActionSize] = useState<ButtonSize>("sm");
  const [emptyActionUseIcon, setEmptyActionUseIcon] = useState(false);
  const [emptyActionLeadingIcon, setEmptyActionLeadingIcon] =
    useState<IconName>("Plus");

  return (
    <PlaygroundSection
      title="Empty States"
      label="[EmptyState]"
      description="Use Tailwind empty states with tone, icon, and action controls."
      controls={
        <div className="space-y-4 text-sm">
          <div className="grid gap-3 md:grid-cols-2">
            <label className="flex flex-col gap-2">
              <span>Tone</span>
              <MultiToggle
                fullWidth
                options={alertToneOptions}
                value={emptyTone}
                size="sm"
                onChange={(value) => setEmptyTone(value as EmptyStateTone)}
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Action variant</span>
              <MultiToggle
                fullWidth
                options={buttonVariantOptions}
                value={emptyActionVariant}
                size="sm"
                onChange={(value) =>
                  setEmptyActionVariant(value as ButtonVariant)
                }
              />
            </label>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="flex flex-col gap-2">
              <span>Action color</span>
              <MultiToggle
                fullWidth
                options={colorOptions}
                value={emptyActionColor}
                size="sm"
                onChange={(value) => setEmptyActionColor(value as ButtonColor)}
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Action size</span>
              <MultiToggle
                fullWidth
                options={buttonSizeOptions}
                value={emptyActionSize}
                size="sm"
                onChange={(value) => setEmptyActionSize(value as ButtonSize)}
              />
            </label>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="flex flex-col gap-2">
              <span>Button label</span>
              <input
                type="text"
                className="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
                value={emptyButtonText}
                onChange={(event) => setEmptyButtonText(event.target.value)}
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Leading icon name</span>
              <input
                type="text"
                className="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900 disabled:opacity-50"
                value={emptyActionLeadingIcon}
                onChange={(event) =>
                  setEmptyActionLeadingIcon(event.target.value as IconName)
                }
                disabled={!emptyActionUseIcon}
              />
            </label>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <label className="flex flex-col gap-2">
              <span>Title</span>
              <input
                type="text"
                className="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
                value={emptyTitle}
                onChange={(event) => setEmptyTitle(event.target.value)}
              />
            </label>
            <label className="flex flex-col gap-2">
              <span>Subtitle</span>
              <textarea
                rows={3}
                className="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
                value={emptySubtitle}
                onChange={(event) => setEmptySubtitle(event.target.value)}
              />
            </label>
          </div>
          <div className="grid gap-2 md:grid-cols-3">
            {[
              {
                label: "Show subtitle",
                value: emptyShowSubtitle,
                setter: setEmptyShowSubtitle,
              },
              {
                label: "Show icon",
                value: emptyShowIcon,
                setter: setEmptyShowIcon,
              },
              {
                label: "Show action",
                value: emptyShowAction,
                setter: setEmptyShowAction,
              },
              {
                label: "Full width",
                value: emptyFullWidth,
                setter: setEmptyFullWidth,
              },
              {
                label: "Leading icon",
                value: emptyActionUseIcon,
                setter: setEmptyActionUseIcon,
              },
            ].map((option) => (
              <label
                key={option.label}
                className="flex items-center justify-between"
              >
                <span>{option.label}</span>
                <Toggle
                  size="sm"
                  checked={option.value}
                  onChange={(event) => option.setter(event.target.checked)}
                />
              </label>
            ))}
          </div>
        </div>
      }
      preview={
        <EmptyState
          className={emptyFullWidth ? undefined : "mx-auto max-w-xl"}
          tone={emptyTone}
          title={emptyTitle || "Empty state title"}
          subtitle={emptyShowSubtitle ? emptySubtitle || undefined : undefined}
          showIcon={emptyShowIcon}
          actionLabel={
            emptyShowAction ? emptyButtonText || "Create item" : undefined
          }
          onAction={
            emptyShowAction
              ? () => console.log("Empty state action clicked")
              : undefined
          }
          actionVariant={emptyActionVariant}
          actionColor={emptyActionColor}
          actionSize={emptyActionSize}
          actionLeadingIcon={
            emptyActionUseIcon ? emptyActionLeadingIcon : undefined
          }
        />
      }
    />
  );
};

// vue/demo/src/pages/UxDemo/demos/EmptyStateDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import { EmptyState, MultiToggle, Toggle } from "@cjlapao/ui-kit-vue";
import type {
  EmptyStateProps,
  ButtonVariant,
  ButtonColor,
  ButtonSize,
  IconName,
} from "@cjlapao/ui-kit-vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import {
  alertToneOptions,
  buttonVariantOptions,
  colorOptions,
  buttonSizeOptions,
} from "../constants";

type EmptyStateTone = EmptyStateProps["tone"];

const emptyTone = ref<EmptyStateTone>("neutral");
const emptyTitle = ref("All caught up");
const emptySubtitle = ref(
  "Connect your first workspace or import data to see activity here.",
);
const emptyShowSubtitle = ref(true);
const emptyShowIcon = ref(true);
const emptyShowAction = ref(true);
const emptyButtonText = ref("Create workspace");
const emptyActionVariant = ref<ButtonVariant>("soft");
const emptyActionColor = ref<ButtonColor>("blue");
const emptyFullWidth = ref(false);
const emptyActionSize = ref<ButtonSize>("sm");
const emptyActionUseIcon = ref(false);
// "Plus" matches the React demo; it is not in the registry, so CustomIcon
// renders its fallback badge — same visible behavior as the React app.
const emptyActionLeadingIcon = ref<IconName>("Plus" as IconName);

const toggleOptions = [
  { label: "Show subtitle", model: emptyShowSubtitle },
  { label: "Show icon", model: emptyShowIcon },
  { label: "Show action", model: emptyShowAction },
  { label: "Full width", model: emptyFullWidth },
  { label: "Leading icon", model: emptyActionUseIcon },
];
</script>

<template>
  <PlaygroundSection
    title="Empty States"
    label="[EmptyState]"
    description="Use Tailwind empty states with tone, icon, and action controls."
  >
    <template #controls>
      <div class="space-y-4 text-sm">
        <div class="grid gap-3 md:grid-cols-2">
          <label class="flex flex-col gap-2">
            <span>Tone</span>
            <MultiToggle
              full-width
              :options="alertToneOptions"
              :model-value="emptyTone ?? 'neutral'"
              size="sm"
              @update:model-value="emptyTone = $event as EmptyStateTone"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Action variant</span>
            <MultiToggle
              full-width
              :options="buttonVariantOptions"
              :model-value="emptyActionVariant"
              size="sm"
              @update:model-value="emptyActionVariant = $event as ButtonVariant"
            />
          </label>
        </div>
        <div class="grid gap-3 md:grid-cols-2">
          <label class="flex flex-col gap-2">
            <span>Action color</span>
            <MultiToggle
              full-width
              :options="colorOptions"
              :model-value="emptyActionColor"
              size="sm"
              @update:model-value="emptyActionColor = $event as ButtonColor"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Action size</span>
            <MultiToggle
              full-width
              :options="buttonSizeOptions"
              :model-value="emptyActionSize"
              size="sm"
              @update:model-value="emptyActionSize = $event as ButtonSize"
            />
          </label>
        </div>
        <div class="grid gap-3 md:grid-cols-2">
          <label class="flex flex-col gap-2">
            <span>Button label</span>
            <input
              type="text"
              class="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
              v-model="emptyButtonText"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Leading icon name</span>
            <input
              type="text"
              class="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900 disabled:opacity-50"
              :value="emptyActionLeadingIcon"
              :disabled="!emptyActionUseIcon"
              @input="
                emptyActionLeadingIcon = (
                  $event.target as HTMLInputElement
                ).value as IconName
              "
            />
          </label>
        </div>
        <div class="grid gap-3 md:grid-cols-2">
          <label class="flex flex-col gap-2">
            <span>Title</span>
            <input
              type="text"
              class="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
              v-model="emptyTitle"
            />
          </label>
          <label class="flex flex-col gap-2">
            <span>Subtitle</span>
            <textarea
              :rows="3"
              class="rounded-lg border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 dark:border-slate-600 dark:bg-slate-900"
              v-model="emptySubtitle"
            />
          </label>
        </div>
        <div class="grid gap-2 md:grid-cols-3">
          <label
            v-for="option in toggleOptions"
            :key="option.label"
            class="flex items-center justify-between"
          >
            <span>{{ option.label }}</span>
            <Toggle
              size="sm"
              :model-value="option.model.value"
              @update:model-value="option.model.value = $event"
            />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <EmptyState
        :class="emptyFullWidth ? undefined : 'mx-auto max-w-xl'"
        :tone="emptyTone"
        :title="emptyTitle || 'Empty state title'"
        :subtitle="emptyShowSubtitle ? emptySubtitle || undefined : undefined"
        :show-icon="emptyShowIcon"
        :action-label="
          emptyShowAction ? emptyButtonText || 'Create item' : undefined
        "
        :on-action="
          emptyShowAction
            ? () => console.log('Empty state action clicked')
            : undefined
        "
        :action-variant="emptyActionVariant"
        :action-color="emptyActionColor"
        :action-size="emptyActionSize"
        :action-leading-icon="
          emptyActionUseIcon ? emptyActionLeadingIcon : undefined
        "
      />
    </template>
  </PlaygroundSection>
</template>
