// react/src/pages/UxDemo/demos/InputGroupDemo.tsx
import React, { useState } from "react";
import { InputGroup, Input, MultiToggle, Toggle } from "../../..";
import { ButtonColor } from "../../..";
import { colorOptions } from "../constants";
import { PlaygroundSection } from "../PlaygroundSection";

export const InputGroupDemo: React.FC = () => {
  const [inputGroupTone, setInputGroupTone] = useState<ButtonColor>("blue");
  const [inputGroupSize, setInputGroupSize] = useState<"sm" | "md" | "lg">(
    "md",
  );
  const [inputGroupLeading, setInputGroupLeading] = useState(true);
  const [inputGroupTrailing, setInputGroupTrailing] = useState(true);

  return (
    <PlaygroundSection
      title="Input Group"
      label="[InputGroup]"
      description="Chain inputs with addons for prefixes/suffixes."
      controls={
        <div className="space-y-4 text-sm">
          <label className="flex flex-col gap-2">
            <span>Tone</span>
            <MultiToggle
              fullWidth
              options={colorOptions}
              value={inputGroupTone}
              size="sm"
              onChange={(value) => setInputGroupTone(value as ButtonColor)}
            />
          </label>
          <label className="flex flex-col gap-2">
            <span>Size</span>
            <MultiToggle
              fullWidth
              options={[
                { label: "SM", value: "sm" },
                { label: "MD", value: "md" },
                { label: "LG", value: "lg" },
              ]}
              value={inputGroupSize}
              size="sm"
              onChange={(value) =>
                setInputGroupSize(value as "sm" | "md" | "lg")
              }
            />
          </label>
          <div className="grid gap-2 md:grid-cols-2">
            <label className="flex items-center justify-between">
              <span>Leading addon</span>
              <Toggle
                size="sm"
                checked={inputGroupLeading}
                onChange={(event) => setInputGroupLeading(event.target.checked)}
              />
            </label>
            <label className="flex items-center justify-between">
              <span>Trailing addon</span>
              <Toggle
                size="sm"
                checked={inputGroupTrailing}
                onChange={(event) =>
                  setInputGroupTrailing(event.target.checked)
                }
              />
            </label>
          </div>
        </div>
      }
      preview={
        <InputGroup
          tone={inputGroupTone}
          size={inputGroupSize}
          leadingAddon={inputGroupLeading ? "https://" : undefined}
          trailingAddon={inputGroupTrailing ? ".example.com" : undefined}
        >
          <Input placeholder="workspace" />
        </InputGroup>
      }
    />
  );
};

// vue/demo/src/pages/UxDemo/demos/InputGroupDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import { InputGroup, Input, MultiToggle, Toggle } from "@cjlapao/ui-kit-vue";
import type { ButtonColor } from "@cjlapao/ui-kit-vue";
import { colorOptions } from "../constants";
import PlaygroundSection from "../PlaygroundSection.vue";

const inputGroupTone = ref<ButtonColor>("blue");
const inputGroupSize = ref<"sm" | "md" | "lg">("md");
const inputGroupLeading = ref(true);
const inputGroupTrailing = ref(true);

const sizeOptions = [
  { label: "SM", value: "sm" },
  { label: "MD", value: "md" },
  { label: "LG", value: "lg" },
];
</script>

<template>
  <PlaygroundSection
    title="Input Group"
    label="[InputGroup]"
    description="Chain inputs with addons for prefixes/suffixes."
  >
    <template #controls>
      <div class="space-y-4 text-sm">
        <label class="flex flex-col gap-2">
          <span>Tone</span>
          <MultiToggle
            full-width
            :options="colorOptions"
            :model-value="inputGroupTone"
            size="sm"
            @update:model-value="inputGroupTone = $event as ButtonColor"
          />
        </label>
        <label class="flex flex-col gap-2">
          <span>Size</span>
          <MultiToggle
            full-width
            :options="sizeOptions"
            :model-value="inputGroupSize"
            size="sm"
            @update:model-value="inputGroupSize = $event as 'sm' | 'md' | 'lg'"
          />
        </label>
        <div class="grid gap-2 md:grid-cols-2">
          <label class="flex items-center justify-between">
            <span>Leading addon</span>
            <Toggle size="sm" v-model="inputGroupLeading" />
          </label>
          <label class="flex items-center justify-between">
            <span>Trailing addon</span>
            <Toggle size="sm" v-model="inputGroupTrailing" />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <InputGroup
        :tone="inputGroupTone"
        :size="inputGroupSize"
        :leading-addon="inputGroupLeading ? 'https://' : undefined"
        :trailing-addon="inputGroupTrailing ? '.example.com' : undefined"
      >
        <Input placeholder="workspace" />
      </InputGroup>
    </template>
  </PlaygroundSection>
</template>
