// demo/src/pages/UxDemo/demos/TableDemo.tsx
// @ts-nocheck
import React, { useState } from "react";
import { PlaygroundSection } from "../PlaygroundSection";
import { Table, Button, IconButton, MultiToggle, Toggle } from "@cjlapao/ui-kit";
import {
  TableVariant,
  TableSortState,
  TableColumn,
} from "@cjlapao/ui-kit";
import { PanelTone } from "@cjlapao/ui-kit";
import { tableVariantOptions, tableToneOptions } from "../constants";

type UserRow = {
  id: string;
  name: string;
  email: string;
  role: "Admin" | "Editor" | "Viewer";
  lastSeen: string;
};

const filledData: UserRow[] = [
  {
    id: "1",
    name: "Sasha G.",
    email: "sasha@company.com",
    role: "Admin",
    lastSeen: "2 hours ago",
  },
  {
    id: "2",
    name: "Kim C.",
    email: "kim@company.com",
    role: "Editor",
    lastSeen: "Yesterday",
  },
  {
    id: "3",
    name: "Lee R.",
    email: "lee@company.com",
    role: "Viewer",
    lastSeen: "Just now",
  },
];

const emptyData: UserRow[] = [];

const columns: TableColumn<UserRow>[] = [
  { id: "name", header: "User", sortable: true },
  { id: "email", header: "Email", sortable: true },
  { id: "role", header: "Role", sortable: true },
  { id: "lastSeen", header: "Last Seen", sortable: true },
];

export const TableDemo: React.FC = () => {
  const [sort, setSort] = useState<TableSortState | null>({
    columnId: "name",
    direction: "asc",
  });
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<UserRow[]>(filledData);
  const [tableVariant, setTableVariant] = useState<TableVariant>("default");
  const [tableTone, setTableTone] = useState<PanelTone>("neutral");
  const [tableStriped, setTableStriped] = useState(true);
  const [tableHoverable, setTableHoverable] = useState(true);

  return (
    <PlaygroundSection
      title="Table"
      label="[Table]"
      description="Data grid with sorting, loading, and tones."
      controls={
        <div className="space-y-4 text-sm">
          <label className="flex flex-col gap-2">
            <span>Variant</span>
            <MultiToggle
              fullWidth
              options={tableVariantOptions}
              value={tableVariant}
              size="sm"
              onChange={(value) => setTableVariant(value as TableVariant)}
            />
          </label>
          <label className="flex flex-col gap-2">
            <span>Tone</span>
            <MultiToggle
              fullWidth
              options={tableToneOptions}
              value={tableTone}
              size="sm"
              onChange={(value) => setTableTone(value as PanelTone)}
            />
          </label>
          <div className="grid gap-2 md:grid-cols-2">
            <label className="flex items-center justify-between">
              <span>Striped rows</span>
              <Toggle
                size="sm"
                checked={tableStriped}
                onChange={(event) => setTableStriped(event.target.checked)}
              />
            </label>
            <label className="flex items-center justify-between">
              <span>Hover state</span>
              <Toggle
                size="sm"
                checked={tableHoverable}
                onChange={(event) => setTableHoverable(event.target.checked)}
              />
            </label>
          </div>
        </div>
      }
      preview={
        <Table<UserRow>
          columns={columns}
          data={data}
          variant={tableVariant}
          tone={tableTone}
          striped={tableStriped}
          hoverable={tableHoverable}
          maxHeight={360}
          loading={loading}
          loadingMessage="Syncing users..."
          loaderProgress={loading ? 42 : undefined}
          sortState={sort}
          onSortChange={setSort}
          rowKey={(row) => row.id}
          onRowClick={(row) => console.log("row clicked", row)}
          headerActions={
            <>
              <Button
                size="sm"
                variant="soft"
                color="blue"
                onClick={() => {
                  setLoading(true);
                  if (data.length === 0) {
                    setData(filledData);
                  }
                  setTimeout(() => setLoading(false), 500);
                }}
              >
                Refresh
              </Button>
              <IconButton
                icon="Trash"
                size="sm"
                variant="ghost"
                color="blue"
                onClick={() => {
                  setLoading(true);
                  setData(emptyData);
                  setTimeout(() => setLoading(false), 500);
                }}
              />
            </>
          }
          footer={<span>Showing {data.length} users</span>}
          emptyState="No users found"
        />
      }
    />
  );
};

// vue/demo/src/pages/UxDemo/demos/TableDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  Table,
  Button,
  IconButton,
  MultiToggle,
  Toggle,
  type TableVariant,
  type TableSortState,
  type TableColumn,
  type PanelTone,
} from "@cjlapao/ui-kit-vue";
import PlaygroundSection from "../PlaygroundSection.vue";
import { tableVariantOptions, tableToneOptions } from "../constants";

type UserRow = {
  id: string;
  name: string;
  email: string;
  role: "Admin" | "Editor" | "Viewer";
  lastSeen: string;
};

const filledData: UserRow[] = [
  {
    id: "1",
    name: "Sasha G.",
    email: "sasha@company.com",
    role: "Admin",
    lastSeen: "2 hours ago",
  },
  {
    id: "2",
    name: "Kim C.",
    email: "kim@company.com",
    role: "Editor",
    lastSeen: "Yesterday",
  },
  {
    id: "3",
    name: "Lee R.",
    email: "lee@company.com",
    role: "Viewer",
    lastSeen: "Just now",
  },
];

const emptyData: UserRow[] = [];

const columns: TableColumn<UserRow>[] = [
  { id: "name", header: "User", sortable: true },
  { id: "email", header: "Email", sortable: true },
  { id: "role", header: "Role", sortable: true },
  { id: "lastSeen", header: "Last Seen", sortable: true },
];

const sort = ref<TableSortState | null>({
  columnId: "name",
  direction: "asc",
});
const loading = ref(false);
const data = ref<UserRow[]>(filledData);
const tableVariant = ref<TableVariant>("default");
const tableTone = ref<PanelTone>("neutral");
const tableStriped = ref(true);
const tableHoverable = ref(true);

const handleRefresh = () => {
  loading.value = true;
  if (data.value.length === 0) {
    data.value = filledData;
  }
  setTimeout(() => (loading.value = false), 500);
};

const handleClear = () => {
  loading.value = true;
  data.value = emptyData;
  setTimeout(() => (loading.value = false), 500);
};

const handleRowClick = (row: UserRow) => {
  console.log("row clicked", row);
};
</script>

<template>
  <PlaygroundSection
    title="Table"
    label="[Table]"
    description="Data grid with sorting, loading, and tones."
  >
    <template #controls>
      <div class="space-y-4 text-sm">
        <label class="flex flex-col gap-2">
          <span>Variant</span>
          <MultiToggle
            full-width
            :options="tableVariantOptions"
            :model-value="tableVariant"
            size="sm"
            @update:model-value="
              (value: string) => (tableVariant = value as TableVariant)
            "
          />
        </label>
        <label class="flex flex-col gap-2">
          <span>Tone</span>
          <MultiToggle
            full-width
            :options="tableToneOptions"
            :model-value="tableTone"
            size="sm"
            @update:model-value="
              (value: string) => (tableTone = value as PanelTone)
            "
          />
        </label>
        <div class="grid gap-2 md:grid-cols-2">
          <label class="flex items-center justify-between">
            <span>Striped rows</span>
            <Toggle size="sm" v-model="tableStriped" />
          </label>
          <label class="flex items-center justify-between">
            <span>Hover state</span>
            <Toggle size="sm" v-model="tableHoverable" />
          </label>
        </div>
      </div>
    </template>
    <template #preview>
      <Table
        :columns="columns"
        :data="data"
        :variant="tableVariant"
        :tone="tableTone"
        :striped="tableStriped"
        :hoverable="tableHoverable"
        :max-height="360"
        :loading="loading"
        loading-message="Syncing users..."
        :loader-progress="loading ? 42 : undefined"
        :sort-state="sort ?? undefined"
        :row-key="(row: UserRow) => row.id"
        empty-state="No users found"
        @sort-change="(value: TableSortState | null) => (sort = value)"
        @row-click="handleRowClick"
      >
        <template #headerActions>
          <Button size="sm" variant="soft" color="blue" @click="handleRefresh">
            Refresh
          </Button>
          <IconButton
            icon="Trash"
            size="sm"
            variant="ghost"
            color="blue"
            @click="handleClear"
          />
        </template>
        <template #footer>
          <span>Showing {{ data.length }} users</span>
        </template>
      </Table>
    </template>
  </PlaygroundSection>
</template>
